const FRASI_RUOTA = [

    // ── STORIA ────────────────────────────────────────────────────────
    { frase: "GIULIO CESARE FU ASSASSINATO", categoria: "Storia" },
    { frase: "GALILEO GALILEI E IL CANNOCCHIALE", categoria: "Storia" },
    { frase: "CRISTOFORO COLOMBO SCOPRI L AMERICA", categoria: "Storia" },
    { frase: "LA NASCITA DELLA REPUBBLICA ITALIANA", categoria: "Storia" },
    { frase: "NAPOLEONE ESILIATO A SANT ELENA", categoria: "Storia" },
    { frase: "I VICHINGHI SOLCARONO I MARI DEL NORD", categoria: "Storia" },
    { frase: "LA MAGNA CHARTA IN INGHILTERRA", categoria: "Storia" },
    { frase: "SPARTACO GUIDO LA RIVOLTA DEGLI SCHIAVI", categoria: "Storia" },
    { frase: "FEDERICO BARBAROSSA CONTRO I COMUNI", categoria: "Storia" },
    { frase: "LA CONQUISTA DI COSTANTINOPOLI", categoria: "Storia" },
    { frase: "ALESSANDRO MAGNO CONQUISTO IL MONDO", categoria: "Storia" },
    { frase: "IL FORO ROMANO CENTRO DELLA CITTA", categoria: "Storia" },
    { frase: "GIULIO CESARE PASSA IL RUBICONE", categoria: "Storia" },
    { frase: "NAPOLEONE SI INCORONA DA SOLO", categoria: "Storia" },
    { frase: "LA GUERRA DI INDIPENDENZA AMERICANA", categoria: "Storia" },
    { frase: "ABRAMO LINCOLN ABOLISCE LA SCHIAVITU", categoria: "Storia" },
    { frase: "CAMILLO BENSO CONTE DI CAVOUR", categoria: "Storia" },
    { frase: "LA RIVOLUZIONE RUSSA DI OTTOBRE", categoria: "Storia" },
    { frase: "IL COLOSSEO COSTRUITO DAI ROMANI", categoria: "Storia" },
    { frase: "MARIA ANTONIETTA GHIGLIOTTINATA", categoria: "Storia" },
    { frase: "LA CROCIATA PER LA TERRA SANTA", categoria: "Storia" },
    { frase: "PLATONE FONDA L ACCADEMIA DI ATENE", categoria: "Storia" },
    { frase: "LA COSTITUZIONE ITALIANA DEL 1948", categoria: "Storia" },
    { frase: "LA DECOLONIZZAZIONE DELL AFRICA", categoria: "Storia" },
    { frase: "MARTIN LUTHER KING HA UN SOGNO", categoria: "Storia" },
    { frase: "LA RIVOLUZIONE CUBANA DI CASTRO", categoria: "Storia" },
    { frase: "NEIL ARMSTRONG CAMMINA SULLA LUNA", categoria: "Storia" },
    { frase: "LA DICHIARAZIONE DEI DIRITTI DELL UOMO", categoria: "Storia" },
    { frase: "L EUROPA UNITA CON MAASTRICHT", categoria: "Storia" },
    { frase: "L ATTENTATO ALLE TORRI GEMELLE", categoria: "Storia" },
    { frase: "MICHELANGELO AFFRESCA LA SISTINA", categoria: "Storia" },
    { frase: "LEONARDO DA VINCI DIPINGE LA GIOCONDA", categoria: "Storia" },
    { frase: "MAGELLANO CIRCUMNAVIGA LA TERRA", categoria: "Storia" },
    { frase: "VASCO DE GAMA RAGGIUNGE L INDIA", categoria: "Storia" },
    { frase: "LA COLONIZZAZIONE DELLE AMERICHE", categoria: "Storia" },
    { frase: "LA RIFORMA PROTESTANTE DI LUTERO", categoria: "Storia" },
    { frase: "ENRICO IV SALITO SUL TRONO DI FRANCIA", categoria: "Storia" },
    { frase: "ELISABETTA I REGINA D INGHILTERRA", categoria: "Storia" },
    { frase: "CROMWELL E LA RIVOLUZIONE INGLESE", categoria: "Storia" },
    { frase: "LUIGI XIV IL RE SOLE DI VERSAILLES", categoria: "Storia" },
    // ── PROVERBI E MODI DI DIRE ────────────────────────────────────────────────────────
    { frase: "TUTTO E BENE QUEL CHE FINISCE BENE", categoria: "Proverbi e Modi di Dire" },
    { frase: "PAESE CHE VAI USANZA CHE TROVI", categoria: "Proverbi e Modi di Dire" },
    { frase: "NON E TUTTO ORO QUELLO CHE LUCCICA", categoria: "Proverbi e Modi di Dire" },
    { frase: "A BUON INTENDITOR POCHE PAROLE", categoria: "Proverbi e Modi di Dire" },
    { frase: "IL LUPO PERDE IL PELO MA NON IL VIZIO", categoria: "Proverbi e Modi di Dire" },
    { frase: "OCCHIO NON VEDE CUORE NON DUOLE", categoria: "Proverbi e Modi di Dire" },
    { frase: "CHI TROVA UN AMICO TROVA UN TESORO", categoria: "Proverbi e Modi di Dire" },
    { frase: "FARE IL PASSO PIU LUNGO DELLA GAMBA", categoria: "Proverbi e Modi di Dire" },
    { frase: "PRENDERE DUE PICCIONI CON UNA FAVA", categoria: "Proverbi e Modi di Dire" },
    { frase: "COSTARE UN OCCHIO DELLA TESTA", categoria: "Proverbi e Modi di Dire" },
    { frase: "UN UOVO OGGI VALE UNA GALLINA DOMANI", categoria: "Proverbi e Modi di Dire" },
    { frase: "CHI SEMINA VENTO RACCOGLIE TEMPESTA", categoria: "Proverbi e Modi di Dire" },
    { frase: "L ERBA DEL VICINO E SEMPRE PIU VERDE", categoria: "Proverbi e Modi di Dire" },
    { frase: "GALLINA VECCHIA FA BUON BRODO", categoria: "Proverbi e Modi di Dire" },
    { frase: "FARE IL BELLO E IL CATTIVO TEMPO", categoria: "Proverbi e Modi di Dire" },
    { frase: "METTERE I BASTONI TRA LE RUOTE", categoria: "Proverbi e Modi di Dire" },
    { frase: "UN COLPO AL CERCHIO E UNO ALLA BOTTE", categoria: "Proverbi e Modi di Dire" },
    { frase: "NON VENDERE LA PELLE DELL ORSO", categoria: "Proverbi e Modi di Dire" },
    { frase: "RIMANDARE ALLE CALENDE GRECHE", categoria: "Proverbi e Modi di Dire" },
    { frase: "NON TUTTE LE CIAMBELLE RIESCONO COL BUCO", categoria: "Proverbi e Modi di Dire" },
    { frase: "TOGLIERSI UN SASSOLINO DALLA SCARPA", categoria: "Proverbi e Modi di Dire" },
    { frase: "CHI VUOLE LA BARCA A VELA LA TIENI", categoria: "Proverbi e Modi di Dire" },
    { frase: "DI PANCIA PIENA SI PARLA A LUNGO", categoria: "Proverbi e Modi di Dire" },
    { frase: "CHI VA PIANO VA SANO E VA LONTANO", categoria: "Proverbi e Modi di Dire" },
    { frase: "IN CASA DI IMPICCATO NON SI PARLA DI FUNE", categoria: "Proverbi e Modi di Dire" },
    { frase: "CHI TARDI ARRIVA MALE ALLOGGIA", categoria: "Proverbi e Modi di Dire" },
    { frase: "TRA IL DIRE E IL FARE C E DI MEZZO IL MARE", categoria: "Proverbi e Modi di Dire" },
    { frase: "NON SI PUO AVERE LA BOTTE PIENA E LA MOGLIE UBRIACA", categoria: "Proverbi e Modi di Dire" },
    { frase: "PRENDERE LUCCIOLE PER LANTERNE", categoria: "Proverbi e Modi di Dire" },
    { frase: "TROVARE IL BANDOLO DELLA MATASSA", categoria: "Proverbi e Modi di Dire" },
    { frase: "SUDARE LE PROVERBIALI SETTE CAMICIE", categoria: "Proverbi e Modi di Dire" },
    // ── LIBRI ────────────────────────────────────────────────────────
    { frase: "DIVINA COMMEDIA DI DANTE ALIGHIERI", categoria: "Libri" },
    { frase: "SE QUESTO E UN UOMO DI PRIMO LEVI", categoria: "Libri" },
    { frase: "DELITTO E CASTIGO DI DOSTOEVSKI", categoria: "Libri" },
    { frase: "ALICE NEL PAESE DELLE MERAVIGLIE", categoria: "Libri" },
    { frase: "FRANKENSTEIN DI MARY SHELLEY", categoria: "Libri" },
    { frase: "IL BARONE RAMPANTE DI CALVINO", categoria: "Libri" },
    { frase: "ROMEO E GIULIETTA DI SHAKESPEARE", categoria: "Libri" },
    { frase: "IL GIOVANE HOLDEN DI SALINGER", categoria: "Libri" },
    { frase: "IL GRANDE GATSBY DI FITZGERALD", categoria: "Libri" },
    { frase: "IL BUIO OLTRE LA SIEPE DI HARPER LEE", categoria: "Libri" },
    { frase: "IL DOTTOR ZIVAGO DI PASTERNAK", categoria: "Libri" },
    { frase: "LE CITTA INVISIBILI DI CALVINO", categoria: "Libri" },
    { frase: "SE UNA NOTTE D INVERNO UN VIAGGIATORE", categoria: "Libri" },
    { frase: "ANNA FRANK IL DIARIO DI UNA RAGAZZA", categoria: "Libri" },
    { frase: "IL DESERTO DEI TARTARI DI BUZZATI", categoria: "Libri" },
    { frase: "UNA QUESTIONE PRIVATA DI FENOGLIO", categoria: "Libri" },
    { frase: "OLIVER TWIST DI CHARLES DICKENS", categoria: "Libri" },
    { frase: "JANE EYRE DI CHARLOTTE BRONTE", categoria: "Libri" },
    { frase: "CIME TEMPESTOSE DI EMILY BRONTE", categoria: "Libri" },
    { frase: "LE AVVENTURE DI HUCKLEBERRY FINN", categoria: "Libri" },
    { frase: "LA LETTERA SCARLATTA DI HAWTHORNE", categoria: "Libri" },
    { frase: "IL MAESTRO E MARGHERITA DI BULGAKOV", categoria: "Libri" },
    { frase: "LA MONTAGNA INCANTATA DI MANN", categoria: "Libri" },
    { frase: "IL SISTEMA PERIODICO DI PRIMO LEVI", categoria: "Libri" },
    { frase: "IL GATTOPARDO DI TOMASI DI LAMPEDUSA", categoria: "Libri" },
    { frase: "FERITO A MORTE DI RAFFAELE LA CAPRIA", categoria: "Libri" },
    { frase: "LE AVVENTURE DI SHERLOCK HOLMES", categoria: "Libri" },
    { frase: "DIECI PICCOLI INDIANI DI CHRISTIE", categoria: "Libri" },
    { frase: "ASSASSINIO SULL ORIENTE EXPRESS", categoria: "Libri" },
    { frase: "IL CODICE DA VINCI DI DAN BROWN", categoria: "Libri" },
    { frase: "HARRY POTTER E LA PIETRA FILOSOFALE", categoria: "Libri" },
    { frase: "LA BELLA ADDORMENTATA NEL BOSCO", categoria: "Libri" },
    { frase: "CENERENTOLA E LA SCARPETTA DI CRISTALLO", categoria: "Libri" },
    { frase: "IL BRUTTO ANATROCCOLO DI ANDERSEN", categoria: "Libri" },
    { frase: "PIPPI CALZELUNGHE DI LINDGREN", categoria: "Libri" },
    { frase: "IL LIBRO DELLA GIUNGLA DI KIPLING", categoria: "Libri" },
    // ── CINEMA E ATTORI ────────────────────────────────────────────────────────
    { frase: "FEDERICO FELLINI IL MAESTRO DEL CINEMA", categoria: "Cinema e Attori" },
    { frase: "SOPHIA LOREN DIVA DEL CINEMA ITALIANO", categoria: "Cinema e Attori" },
    { frase: "ROBERTO BENIGNI HA VINTO L OSCAR", categoria: "Cinema e Attori" },
    { frase: "IL PADRINO DI FRANCIS FORD COPPOLA", categoria: "Cinema e Attori" },
    { frase: "CHARLIE CHAPLIN INVENTORE DI CHARLOT", categoria: "Cinema e Attori" },
    { frase: "ALBERTO SORDI IL RE DELLA COMMEDIA", categoria: "Cinema e Attori" },
    { frase: "LA GRANDE BELLEZZA VINCE L OSCAR", categoria: "Cinema e Attori" },
    { frase: "JAMES DEAN RIBELLE SENZA UNA CAUSA", categoria: "Cinema e Attori" },
    { frase: "AUDREY HEPBURN IN COLAZIONE DA TIFFANY", categoria: "Cinema e Attori" },
    { frase: "MERYL STREEP LA MIGLIORE ATTRICE", categoria: "Cinema e Attori" },
    { frase: "CLINT EASTWOOD REGISTA E ATTORE", categoria: "Cinema e Attori" },
    { frase: "WALT DISNEY IL PADRE DI TOPOLINO", categoria: "Cinema e Attori" },
    { frase: "MARILYN MONROE LA BIONDA D AMERICA", categoria: "Cinema e Attori" },
    { frase: "STANLEY KUBRICK VISIONARIO DEL CINEMA", categoria: "Cinema e Attori" },
    { frase: "STEVEN SPIELBERG HA GIRATO SCHINDLER", categoria: "Cinema e Attori" },
    { frase: "TOTO IL PRINCIPE DELLA RISATA", categoria: "Cinema e Attori" },
    { frase: "IL FESTIVAL DEL CINEMA DI VENEZIA", categoria: "Cinema e Attori" },
    { frase: "MARLON BRANDO IN APOCALYPSE NOW", categoria: "Cinema e Attori" },
    { frase: "SERGIO LEONE E IL WESTERN ALL ITALIANA", categoria: "Cinema e Attori" },
    { frase: "ROMAN POLANSKI REGISTA POLACCO", categoria: "Cinema e Attori" },
    { frase: "PIER PAOLO PASOLINI INTELLETTUALE", categoria: "Cinema e Attori" },
    { frase: "VISCONTI IL GATTOPARDO SUL GRANDE SCHERMO", categoria: "Cinema e Attori" },
    { frase: "BERNARDO BERTOLUCCI REGISTA ITALIANO", categoria: "Cinema e Attori" },
    { frase: "ETTORE SCOLA RACCONTAVA L ITALIA", categoria: "Cinema e Attori" },
    { frase: "GABRIELE SALVATORES OSCARS CON MEDITERRANEO", categoria: "Cinema e Attori" },
    { frase: "VITTORIO DE SICA LADRI DI BICICLETTE", categoria: "Cinema e Attori" },
    { frase: "ANNA MAGNANI OSCAR NEL DOPOGUERRA", categoria: "Cinema e Attori" },
    { frase: "MARCELLO MASTROIANNI ATTORE ROMANO", categoria: "Cinema e Attori" },
    { frase: "MONICA BELLUCCI BELLEZZA ITALIANA", categoria: "Cinema e Attori" },
    { frase: "PLACIDO POLANSKI GINOCCHIO DI CLAIRE", categoria: "Cinema e Attori" },
    { frase: "ALFRED HITCHCOCK MAESTRO DEL BRIVIDO", categoria: "Cinema e Attori" },
    { frase: "VIA COL VENTO CON VIVIEN LEIGH", categoria: "Cinema e Attori" },
    { frase: "CASABLANCA CON HUMPHREY BOGART", categoria: "Cinema e Attori" },
    { frase: "SCHINDLER S LIST DI SPIELBERG", categoria: "Cinema e Attori" },
    { frase: "TAXI DRIVER DI MARTIN SCORSESE", categoria: "Cinema e Attori" },
    { frase: "IL GLADIATORE CON RUSSELL CROWE", categoria: "Cinema e Attori" },
    { frase: "AVATAR IL FILM PIU VISTO DEL MONDO", categoria: "Cinema e Attori" },
    { frase: "STAR WARS LA FORZA CHE CI SIA CON TE", categoria: "Cinema e Attori" },
    { frase: "IL SIGNORE DEGLI ANELLI AL CINEMA", categoria: "Cinema e Attori" },
    { frase: "PULP FICTION DI QUENTIN TARANTINO", categoria: "Cinema e Attori" },
    { frase: "GOODFELLAS DI MARTIN SCORSESE", categoria: "Cinema e Attori" },
    { frase: "IL DOTTOR STRANAMORE DI KUBRICK", categoria: "Cinema e Attori" },
    { frase: "ARANCIA MECCANICA DI KUBRICK", categoria: "Cinema e Attori" },
    { frase: "IL TRONO DI SPADE NELLA SERIE TV", categoria: "Cinema e Attori" },
    { frase: "BREAKING BAD SERIE TELEVISIVA", categoria: "Cinema e Attori" },
    { frase: "AMARCORD DI FEDERICO FELLINI", categoria: "Cinema e Attori" },
    { frase: "CINEMA PARADISO OSCARS DI TORNATORE", categoria: "Cinema e Attori" },
    // ── MUSICA ────────────────────────────────────────────────────────
    { frase: "BEETHOVEN COMPOSE LA NONA SINFONIA", categoria: "Musica" },
    { frase: "MOZART BAMBINO PRODIGIO DI SALISBURGO", categoria: "Musica" },
    { frase: "LUCIO BATTISTI ICONA DELLA MUSICA", categoria: "Musica" },
    { frase: "LA TRAVIATA DI GIUSEPPE VERDI", categoria: "Musica" },
    { frase: "FREDDIE MERCURY VOCE DEI QUEEN", categoria: "Musica" },
    { frase: "ANDREA BOCELLI TENORE DI FAMA MONDIALE", categoria: "Musica" },
    { frase: "I BEATLES RIVOLUZIONARONO LA MUSICA", categoria: "Musica" },
    { frase: "IL VIOLINO DI NICOLO PAGANINI", categoria: "Musica" },
    { frase: "FRANK SINATRA LA PIU BELLA VOCE", categoria: "Musica" },
    { frase: "LUIGI BOCCHERINI COMPOSITORE TOSCANO", categoria: "Musica" },
    { frase: "DAVID BOWIE IL CAMALEONTE DEL ROCK", categoria: "Musica" },
    { frase: "EROS RAMAZZOTTI CANTANTE ITALIANO", categoria: "Musica" },
    { frase: "VASCO ROSSI IL ROCKER DI ZOCCA", categoria: "Musica" },
    { frase: "ROSSINI IL BARBIERE DI SIVIGLIA", categoria: "Musica" },
    { frase: "CHOPIN IL POETA DEL PIANOFORTE", categoria: "Musica" },
    { frase: "LISZT IL VIRTUOSO DEL PIANOFORTE", categoria: "Musica" },
    { frase: "SCHUBERT LA TROTA E LA SINFONIA", categoria: "Musica" },
    { frase: "VERDI E IL MELODRAMMA ITALIANO", categoria: "Musica" },
    { frase: "MAHLER SINFONIE MONUMENTALI", categoria: "Musica" },
    { frase: "STRAVINSKIJ IL RITO DELLA PRIMAVERA", categoria: "Musica" },
    { frase: "BACH IL CLAVICEMBALO BEN TEMPERATO", categoria: "Musica" },
    { frase: "JIMI HENDRIX IL GENIO DELLA CHITARRA", categoria: "Musica" },
    { frase: "PINK FLOYD THE DARK SIDE OF THE MOON", categoria: "Musica" },
    { frase: "THE ROLLING STONES ROCK SENZA ETA", categoria: "Musica" },
    { frase: "BOB DYLAN PREMIO NOBEL PER LA LETTERATURA", categoria: "Musica" },
    { frase: "ADELE LA VOCE PIU BELLA D INGHILTERRA", categoria: "Musica" },
    { frase: "AMY WINEHOUSE VOCE IMMORTALE", categoria: "Musica" },
    { frase: "LUCIO DALLA BOLOGNESE SENZA CONFINI", categoria: "Musica" },
    { frase: "PINO DANIELE NAPOLI NEL CUORE", categoria: "Musica" },
    { frase: "FABRIZIO DE ANDRE IL CANTAUTORE", categoria: "Musica" },
    { frase: "GIORGIO GABER IL TEATRO CANZONE", categoria: "Musica" },
    { frase: "FRANCO BATTIATO MUSICA SPIRITUALE", categoria: "Musica" },
    { frase: "DOMENICO MODUGNO VOLARE NEL BLU", categoria: "Musica" },
    { frase: "CLAUDIO VILLA IL RE DELLA CANZONE", categoria: "Musica" },
    // ── ASTRONOMIA ────────────────────────────────────────────────────────
    { frase: "IL SOLE E UNA STELLA NANA GIALLA", categoria: "Astronomia" },
    { frase: "LA LUNA E IL SATELLITE DELLA TERRA", categoria: "Astronomia" },
    { frase: "LA VIA LATTEA E LA NOSTRA GALASSIA", categoria: "Astronomia" },
    { frase: "NETTUNO IL PIANETA PIU LONTANO", categoria: "Astronomia" },
    { frase: "UN ANNO LUCE E L UNITA DI MISURA", categoria: "Astronomia" },
    { frase: "I BUCHI NERI ASSORBONO LA LUCE", categoria: "Astronomia" },
    { frase: "NEIL ARMSTRONG PRIMO UOMO SULLA LUNA", categoria: "Astronomia" },
    { frase: "LA STAZIONE SPAZIALE INTERNAZIONALE", categoria: "Astronomia" },
    { frase: "IL TELESCOPIO SPAZIALE HUBBLE", categoria: "Astronomia" },
    { frase: "GLI ASTRONAUTI ORBITANO LA TERRA", categoria: "Astronomia" },
    { frase: "LE STELLE CADENTI SONO METEORITI", categoria: "Astronomia" },
    { frase: "IL BIG BANG ALL ORIGINE DI TUTTO", categoria: "Astronomia" },
    { frase: "MARTE HA DUE LUNE PHOBOS E DEIMOS", categoria: "Astronomia" },
    { frase: "MERCURIO E IL PIANETA PIU VICINO AL SOLE", categoria: "Astronomia" },
    { frase: "LA NEBULOSA E UNA CULLA DI STELLE", categoria: "Astronomia" },
    { frase: "LE SUPERNOVE ESPLODONO NELLO SPAZIO", categoria: "Astronomia" },
    { frase: "LE PULSAR SONO STELLE DI NEUTRONI", categoria: "Astronomia" },
    { frase: "I QUASAR EMETTONO ENERGIA ENORME", categoria: "Astronomia" },
    { frase: "LA FORZA DI GRAVITA TIENE TUTTO INSIEME", categoria: "Astronomia" },
    { frase: "IL SISTEMA SOLARE HA OTTO PIANETI", categoria: "Astronomia" },
    { frase: "GIOVE HA LA GRANDE MACCHIA ROSSA", categoria: "Astronomia" },
    { frase: "LA CINTURA DI ASTEROIDI TRA MARTE E GIOVE", categoria: "Astronomia" },
    { frase: "SATURNO E MENO DENSO DELL ACQUA", categoria: "Astronomia" },
    { frase: "GAGARIN PRIMO UOMO NELLO SPAZIO", categoria: "Astronomia" },
    { frase: "LO SPUTNIK IL PRIMO SATELLITE ARTIFICIALE", categoria: "Astronomia" },
    { frase: "LA NASA E L AGENZIA SPAZIALE AMERICANA", categoria: "Astronomia" },
    { frase: "L ESA E L AGENZIA SPAZIALE EUROPEA", categoria: "Astronomia" },
    { frase: "ELON MUSK PUNTA A CONQUISTARE MARTE", categoria: "Astronomia" },
    { frase: "IL ROVER PERSEVERANCE SU MARTE", categoria: "Astronomia" },
    { frase: "IL JAMES WEBB TELESCOPIO DEL FUTURO", categoria: "Astronomia" },
    { frase: "ORIONE E UNA COSTELLAZIONE FAMOSA", categoria: "Astronomia" },
    { frase: "LA STELLA POLARE INDICA IL NORD", categoria: "Astronomia" },
    { frase: "LA COMETA PASSA OGNI SETTANTASETTE ANNI", categoria: "Astronomia" },
    { frase: "EUROPA LUNA DI GIOVE HA UN OCEANO", categoria: "Astronomia" },
    { frase: "TITANO LUNA DI SATURNO HA ATMOSFERA", categoria: "Astronomia" },
    { frase: "I METEORITI CADONO SULLA TERRA", categoria: "Astronomia" },
    { frase: "LA MATERIA OSCURA DELL UNIVERSO", categoria: "Astronomia" },
    { frase: "L ENERGIA OSCURA ACCELERA L ESPANSIONE", categoria: "Astronomia" },
    { frase: "LE GALASSIE SI SCONTRANO TRA LORO", categoria: "Astronomia" },
    // ── INVENZIONI ────────────────────────────────────────────────────────
    { frase: "GUGLIELMO MARCONI INVENTO LA RADIO", categoria: "Invenzioni" },
    { frase: "THOMAS EDISON INVENTO LA LAMPADINA", categoria: "Invenzioni" },
    { frase: "ALEXANDER BELL INVENTO IL TELEFONO", categoria: "Invenzioni" },
    { frase: "LA STAMPA DI GUTENBERG CAMBIA IL MONDO", categoria: "Invenzioni" },
    { frase: "JAMES WATT E LA MACCHINA A VAPORE", categoria: "Invenzioni" },
    { frase: "I FRATELLI WRIGHT E L AEROPLANO", categoria: "Invenzioni" },
    { frase: "GALILEO INVENTO IL CANNOCCHIALE", categoria: "Invenzioni" },
    { frase: "ANTONIO MEUCCI CREO IL TELEFONO", categoria: "Invenzioni" },
    { frase: "LOUIS BRAILLE INVENTO L ALFABETO", categoria: "Invenzioni" },
    { frase: "LA PENICILLINA DI ALEXANDER FLEMING", categoria: "Invenzioni" },
    { frase: "NIKOLA TESLA E LA CORRENTE ALTERNATA", categoria: "Invenzioni" },
    { frase: "ALBERT EINSTEIN E LA RELATIVITA", categoria: "Invenzioni" },
    { frase: "LA RUOTA E L INVENZIONE PIU ANTICA", categoria: "Invenzioni" },
    { frase: "IL MOTORE A SCOPPIO CAMBIA I TRASPORTI", categoria: "Invenzioni" },
    { frase: "LA BUSSOLA GUIDA I NAVIGATORI", categoria: "Invenzioni" },
    { frase: "TIM BERNERS LEE INVENTO INTERNET", categoria: "Invenzioni" },
    { frase: "MARIE CURIE SCOPRI LA RADIOATTIVITA", categoria: "Invenzioni" },
    { frase: "CHARLES BABBAGE E IL PROTOTIPO DEL PC", categoria: "Invenzioni" },
    { frase: "ARCHIMEDE SCOPRI IL PRINCIPIO DEI GALLEGGIANTI", categoria: "Invenzioni" },
    { frase: "IL MOTORE A REAZIONE CAMBIA L AVIAZIONE", categoria: "Invenzioni" },
    { frase: "STEVENSON E LA LOCOMOTIVA A VAPORE", categoria: "Invenzioni" },
    { frase: "WRIGHT BROTHERS IL PRIMO VOLO", categoria: "Invenzioni" },
    { frase: "GUTENBERG RIVOLUZIONE LA COMUNICAZIONE", categoria: "Invenzioni" },
    { frase: "IL CALCOLATORE ELETTRONICO ENIAC", categoria: "Invenzioni" },
    { frase: "ALAN TURING IL PADRE DELL INFORMATICA", categoria: "Invenzioni" },
    { frase: "MARK ZUCKERBERG CREA FACEBOOK", categoria: "Invenzioni" },
    { frase: "IL TRANSISTOR CAMBIA L ELETTRONICA", categoria: "Invenzioni" },
    { frase: "IL MICROCHIP RIVOLUZIONA LA TECNOLOGIA", categoria: "Invenzioni" },
    { frase: "IL TELEFONO SENZA FILI DI MARCONI", categoria: "Invenzioni" },
    { frase: "LA TELEVISIONE IN BIANCO E NERO", categoria: "Invenzioni" },
    { frase: "IL FRIGORIFERO RIVOLUZIONA LA CUCINA", categoria: "Invenzioni" },
    { frase: "IL POST IT INVENZIONE ACCIDENTALE", categoria: "Invenzioni" },
    { frase: "LA CARTA UN INVENZIONE CINESE", categoria: "Invenzioni" },
    { frase: "IL MAPAMONDO DI AMERIGO VESPUCCI", categoria: "Invenzioni" },
    { frase: "IL TELESCOPIO CAMBIA L ASTRONOMIA", categoria: "Invenzioni" },
    { frase: "IL MICROSCOPIO SVELA IL MONDO PICCOLO", categoria: "Invenzioni" },
    { frase: "LA MACCHINA FOTOGRAFICA IMMORTALA IL TEMPO", categoria: "Invenzioni" },
    { frase: "IL CINEMA NASCE CON I FRATELLI LUMIERE", categoria: "Invenzioni" },
    // ── GEOGRAFIA E VIAGGI ────────────────────────────────────────────────────────
    { frase: "LA STATUA DELLA LIBERTA A NEW YORK", categoria: "Geografia e Viaggi" },
    { frase: "IL RIO DELLE AMAZZONI IN BRASILE", categoria: "Geografia e Viaggi" },
    { frase: "LA CITTA DI VENEZIA SULL ACQUA", categoria: "Geografia e Viaggi" },
    { frase: "IL MONTE EVEREST LA VETTA PIU ALTA", categoria: "Geografia e Viaggi" },
    { frase: "IL DESERTO DEL SAHARA IN AFRICA", categoria: "Geografia e Viaggi" },
    { frase: "LA GRANDE BARRIERA CORALLINA", categoria: "Geografia e Viaggi" },
    { frase: "FIRENZE LA CULLA DEL RINASCIMENTO", categoria: "Geografia e Viaggi" },
    { frase: "NEW YORK LA CITTA CHE NON DORME MAI", categoria: "Geografia e Viaggi" },
    { frase: "TOKYO LA CAPITALE DEL GIAPPONE", categoria: "Geografia e Viaggi" },
    { frase: "IL NILO IL FIUME PIU LUNGO DEL MONDO", categoria: "Geografia e Viaggi" },
    { frase: "LA GRECIA CULLA DELLA DEMOCRAZIA", categoria: "Geografia e Viaggi" },
    { frase: "LA COSTA AMALFITANA UN PARADISO", categoria: "Geografia e Viaggi" },
    { frase: "IL LAGO DI GARDA IL PIU GRANDE D ITALIA", categoria: "Geografia e Viaggi" },
    { frase: "AMSTERDAM LA CITTA DEI CANALI", categoria: "Geografia e Viaggi" },
    { frase: "MACHU PICCHU CITTA INCA IN PERU", categoria: "Geografia e Viaggi" },
    { frase: "IL MONTE BIANCO AL CONFINE TRA ITALIA E FRANCIA", categoria: "Geografia e Viaggi" },
    { frase: "ISTANBUL PONTE TRA EUROPA E ASIA", categoria: "Geografia e Viaggi" },
    { frase: "LA PATAGONIA AI CONFINI DEL MONDO", categoria: "Geografia e Viaggi" },
    { frase: "LE ISOLE GALAPAGOS IN ECUADOR", categoria: "Geografia e Viaggi" },
    { frase: "LA MURAGLIA CINESE VISTA DALLO SPAZIO", categoria: "Geografia e Viaggi" },
    { frase: "LONDRA LA CAPITALE DEL REGNO UNITO", categoria: "Geografia e Viaggi" },
    { frase: "BERLINO CITTA DIVISA E RIUNITA", categoria: "Geografia e Viaggi" },
    { frase: "DUBAI IL GRATTACIELO PIU ALTO", categoria: "Geografia e Viaggi" },
    { frase: "LA PENISOLA ARABICA NEL GOLFO PERSICO", categoria: "Geografia e Viaggi" },
    { frase: "IL LAGO BAIKAL IL PIU PROFONDO", categoria: "Geografia e Viaggi" },
    { frase: "LA FORESTA AMAZZONICA IN BRASILE", categoria: "Geografia e Viaggi" },
    { frase: "LAS VEGAS NEL DESERTO DEL NEVADA", categoria: "Geografia e Viaggi" },
    { frase: "SAN FRANCISCO E IL GOLDEN GATE", categoria: "Geografia e Viaggi" },
    { frase: "BUENOS AIRES LA PARIGI DEL SUD", categoria: "Geografia e Viaggi" },
    { frase: "CAPE TOWN AI PIEDI DELLA TAVOLA", categoria: "Geografia e Viaggi" },
    { frase: "MUMBAI LA CITTA DEI SOGNI INDIANI", categoria: "Geografia e Viaggi" },
    { frase: "PECHINO LA CAPITALE DELLA CINA", categoria: "Geografia e Viaggi" },
    { frase: "BALI ISOLA DEI TEMPLI E DEI RISI", categoria: "Geografia e Viaggi" },
    { frase: "KYOTO LA CITTA DEI MILLE TEMPLI", categoria: "Geografia e Viaggi" },
    { frase: "L ISLANDA TERRA DI GHIACCIO E FUOCO", categoria: "Geografia e Viaggi" },
    { frase: "LISBONA LA CITTA DELLE SETTE COLLINE", categoria: "Geografia e Viaggi" },
    { frase: "SIVIGLIA CAPITAL DEL FLAMENCO", categoria: "Geografia e Viaggi" },
    { frase: "BRUXELLES CAPITALE DELL EUROPA", categoria: "Geografia e Viaggi" },
    { frase: "MONACO DI BAVIERA E IL FESTIVALBIRRA", categoria: "Geografia e Viaggi" },
    { frase: "SICILIA TERRA DI ARANCINI E SOLE", categoria: "Geografia e Viaggi" },
    // ── IN CUCINA ────────────────────────────────────────────────────────
    { frase: "LA PIZZA MARGHERITA DI NAPOLI", categoria: "In Cucina" },
    { frase: "IL GELATO ARTIGIANALE ITALIANO", categoria: "In Cucina" },
    { frase: "LE ORECCHIETTE ALLE CIME DI RAPA", categoria: "In Cucina" },
    { frase: "LA TORTA CAPRESE AL CIOCCOLATO", categoria: "In Cucina" },
    { frase: "LE ARANCINE DI RISO SICILIANE", categoria: "In Cucina" },
    { frase: "IL CINGHIALE IN UMIDO TOSCANO", categoria: "In Cucina" },
    { frase: "LA ZUPPA DI PESCE ALLA LIVORNESE", categoria: "In Cucina" },
    { frase: "LA PASTIERA NAPOLETANA DI PASQUA", categoria: "In Cucina" },
    { frase: "IL PARMIGIANO REGGIANO STAGIONATO", categoria: "In Cucina" },
    { frase: "IL TALEGGIO CREMOSO LOMBARDO", categoria: "In Cucina" },
    // ── ANIMALI ────────────────────────────────────────────────────────
    { frase: "IL DELFINO E UN MAMMIFERO MARINO", categoria: "Animali" },
    { frase: "L AQUILA VOLA PIU IN ALTO DI TUTTI", categoria: "Animali" },
    { frase: "IL GHEPARDO E L ANIMALE PIU VELOCE", categoria: "Animali" },
    { frase: "LA GIRAFFA HA IL COLLO PIU LUNGO", categoria: "Animali" },
    { frase: "IL PINGUINO VIVE IN ANTARTIDE", categoria: "Animali" },
    { frase: "LA BALENA E IL MAMMIFERO PIU GRANDE", categoria: "Animali" },
    { frase: "LA FARFALLA NASCE DAL BOZZOLO", categoria: "Animali" },
    { frase: "IL FALCO PEREGRINO E VELOCISSIMO", categoria: "Animali" },
    { frase: "LA TARTARUGA VIVE CENTINAIA DI ANNI", categoria: "Animali" },
    { frase: "IL PANDA GIGANTE VIENE DALLA CINA", categoria: "Animali" },
    { frase: "IL CIGNO E IL SIMBOLO DELL ELEGANZA", categoria: "Animali" },
    { frase: "LO SQUALO BIANCO PREDATORE DEI MARI", categoria: "Animali" },
    { frase: "IL FENICOTTERO ROSA SULLE ACQUE", categoria: "Animali" },
    { frase: "LA RANA VIVE IN ACQUA E IN TERRA", categoria: "Animali" },
    { frase: "IL SERPENTE STRISCIA SENZA ZAMPE", categoria: "Animali" },
    { frase: "IL COCCODRILLO HA I DENTI AGUZZI", categoria: "Animali" },
    { frase: "L IPPOPOTAMO NEI FIUMI AFRICANI", categoria: "Animali" },
    { frase: "LA ZEBRA HA STRISCE NERE E BIANCHE", categoria: "Animali" },
    { frase: "IL CAVALLO CORRE VELOCISSIMO", categoria: "Animali" },
    { frase: "LA MUCCA DA IL LATTE OGNI GIORNO", categoria: "Animali" },
    { frase: "IL PAPPAGALLO RIPETE LE PAROLE", categoria: "Animali" },
    { frase: "IL TUCANO HA IL BECCO COLORATO", categoria: "Animali" },
    { frase: "IL RATTO MUSK VIVE NELL ARTICO", categoria: "Animali" },
    { frase: "LA LIBELLULA VOLA SUGLI STAGNI", categoria: "Animali" },
    { frase: "IL CALAMARO SPRUZZA INCHIOSTRO", categoria: "Animali" },
    { frase: "LA STELLA MARINA HA CINQUE BRACCIA", categoria: "Animali" },
    { frase: "IL RICCIO SI ARROTOLA IN PALLA", categoria: "Animali" },
    { frase: "IL CERVO CAMBIA IL PALCO OGNI ANNO", categoria: "Animali" },
    { frase: "IL CAPRIOLO NEI BOSCHI ITALIANI", categoria: "Animali" },
    // ── NELLO SPORT ────────────────────────────────────────────────────────
    { frase: "LA FERRARI REGNA IN FORMULA UNO", categoria: "Nello Sport" },
    { frase: "ROGER FEDERER IL RE DEL TENNIS", categoria: "Nello Sport" },
    { frase: "USAIN BOLT IL VELOCISTA PIU FORTE", categoria: "Nello Sport" },
    { frase: "LA NAZIONALE ITALIANA VINCE I MONDIALI", categoria: "Nello Sport" },
    { frase: "LE OLIMPIADI NASCONO IN GRECIA", categoria: "Nello Sport" },
    { frase: "IL CICLISMO SULLE STRADE D ITALIA", categoria: "Nello Sport" },
    { frase: "IL BASKET INVENTATO DA NAISMITH", categoria: "Nello Sport" },
    { frase: "GIANLUIGI BUFFON IL MIGLIOR PORTIERE", categoria: "Nello Sport" },
    { frase: "LIONEL MESSI RE DEL CALCIO MONDIALE", categoria: "Nello Sport" },
    { frase: "IL RUGBY LO SPORT DEI GUERRIERI", categoria: "Nello Sport" },
    { frase: "FEDERICA PELLEGRINI ORO IN PISCINA", categoria: "Nello Sport" },
    { frase: "FAUSTO COPPI IL CAMPIONISSIMO", categoria: "Nello Sport" },
    { frase: "NOVAK DJOKOVIC CAMPIONE DI TENNIS", categoria: "Nello Sport" },
    { frase: "MILAN E INTER IL DERBY DI MILANO", categoria: "Nello Sport" },
    { frase: "IL SURFING SULLE ONDE DEL PACIFICO", categoria: "Nello Sport" },
    { frase: "RONALDO IL FENOMENO BRASILIANO", categoria: "Nello Sport" },
    { frase: "CRISTIANO RONALDO CINQUE PALLONI D ORO", categoria: "Nello Sport" },
    { frase: "ZLATAN IBRAHIMOVIC IL GIGANTE SVEDESE", categoria: "Nello Sport" },
    { frase: "DIEGO ARMANDO MARADONA LA MANO DI DIO", categoria: "Nello Sport" },
    { frase: "PELE TRE VOLTE CAMPIONE DEL MONDO", categoria: "Nello Sport" },
    { frase: "AYRTON SENNA RE DELLA FORMULA UNO", categoria: "Nello Sport" },
    { frase: "MICHAEL SCHUMACHER SETTE MONDIALI", categoria: "Nello Sport" },
    { frase: "LEWIS HAMILTON SETTE MONDIALI", categoria: "Nello Sport" },
    { frase: "MAX VERSTAPPEN CAMPIONE DEL MONDO", categoria: "Nello Sport" },
    { frase: "SERENA WILLIAMS REGINA DEL TENNIS", categoria: "Nello Sport" },
    { frase: "STEFFI GRAF CAMPIONESSA TEDESCA", categoria: "Nello Sport" },
    { frase: "PETE SAMPRAS SETTE WIMBLEDON", categoria: "Nello Sport" },
    { frase: "RAFAEL NADAL CAMPIONE SULLA TERRA ROSSA", categoria: "Nello Sport" },
    { frase: "LE OLIMPIADI INVERNALI IN MONTAGNA", categoria: "Nello Sport" },
    { frase: "IL BOB A QUATTRO ALLE OLIMPIADI", categoria: "Nello Sport" },
    { frase: "IL DECATHLON REGINA DELL ATLETICA", categoria: "Nello Sport" },
    { frase: "LA MARCIA OLIMPICA SULLE STRADE", categoria: "Nello Sport" },
    { frase: "IL KARATE ALLE OLIMPIADI DI TOKYO", categoria: "Nello Sport" },
    // ── NEL TEMPO LIBERO ────────────────────────────────────────────────────────
    { frase: "ANDARE AL CINEMA IL SABATO SERA", categoria: "Nel Tempo Libero" },
    { frase: "FARE UNA PASSEGGIATA AL PARCO", categoria: "Nel Tempo Libero" },
    { frase: "GUARDARE UN FILM IN STREAMING", categoria: "Nel Tempo Libero" },
    { frase: "CUCINARE UN DOLCE PER LA FAMIGLIA", categoria: "Nel Tempo Libero" },
    { frase: "ASCOLTARE MUSICA SOTTO LE STELLE", categoria: "Nel Tempo Libero" },
    { frase: "DIPINGERE UN QUADRO AD ACQUERELLO", categoria: "Nel Tempo Libero" },
    { frase: "SUONARE LA CHITARRA SUL BALCONE", categoria: "Nel Tempo Libero" },
    { frase: "FARE GIARDINAGGIO IN PRIMAVERA", categoria: "Nel Tempo Libero" },
    { frase: "ANDARE A TEATRO IL VENERDI SERA", categoria: "Nel Tempo Libero" },
    { frase: "SCRIVERE UN DIARIO OGNI GIORNO", categoria: "Nel Tempo Libero" },
    { frase: "GUARDARE LE STELLE CON IL TELESCOPIO", categoria: "Nel Tempo Libero" },
    { frase: "ANDARE A FARE SHOPPING IN CENTRO", categoria: "Nel Tempo Libero" },
    { frase: "VISITARE UNA MOSTRA D ARTE MODERNA", categoria: "Nel Tempo Libero" },
    { frase: "FARE FOTOGRAFIA IN GIRO PER LA CITTA", categoria: "Nel Tempo Libero" },
    { frase: "GIOCARE A SCACCHI CON IL NONNO", categoria: "Nel Tempo Libero" },
    { frase: "COLLEZIONARE VINILI ANNI SETTANTA", categoria: "Nel Tempo Libero" },
    { frase: "FARE CERAMICA AL CORSO SERALE", categoria: "Nel Tempo Libero" },
    { frase: "CUCINARE LA PIZZA NEL FORNO A LEGNA", categoria: "Nel Tempo Libero" },
    { frase: "FARE ARRAMPICATA IN PALESTRA", categoria: "Nel Tempo Libero" },
    { frase: "FARE UNA PASSEGGIATA IN RIVA AL MARE", categoria: "Nel Tempo Libero" },
    { frase: "GUARDARE IL TRAMONTO DAL TERRAZZO", categoria: "Nel Tempo Libero" },
    { frase: "FARE UNA SERATA A GIOCHI DI SOCIETA", categoria: "Nel Tempo Libero" },
    { frase: "ANDARE A UN CONCERTO ALL APERTO", categoria: "Nel Tempo Libero" },
    { frase: "VISITARE UN CASTELLO MEDIEVALE", categoria: "Nel Tempo Libero" },
    { frase: "FARE VOLONTARIATO NEL FINE SETTIMANA", categoria: "Nel Tempo Libero" },
    { frase: "LEGGERE UN FUMETTO IN SPIAGGIA", categoria: "Nel Tempo Libero" },
    { frase: "SEGUIRE UNA SERIE TV SU NETFLIX", categoria: "Nel Tempo Libero" },
    { frase: "FARE UN BAGNO NELLA VASCA GRANDE", categoria: "Nel Tempo Libero" },
    { frase: "COSTRUIRE UN MODELLINO DI NAVE", categoria: "Nel Tempo Libero" },
    { frase: "FARE LA MARMELLATA CON LE PESCHE", categoria: "Nel Tempo Libero" },
    { frase: "RACCOGLIERE FUNGHI NEL BOSCO", categoria: "Nel Tempo Libero" },
    { frase: "FARE UN TOUR IN VESPA PER L ITALIA", categoria: "Nel Tempo Libero" },
    { frase: "SCOPRIRE UN NUOVO RISTORANTE", categoria: "Nel Tempo Libero" },
    { frase: "PREPARARE UN APERITIVO GOURMET", categoria: "Nel Tempo Libero" },
    { frase: "ANDARE AI MERCATINI DI NATALE", categoria: "Nel Tempo Libero" },
    { frase: "FARE UN LABORATORIO DI MOSAICO", categoria: "Nel Tempo Libero" },
    { frase: "FARE UN CORSO DI LINGUA STRANIERA", categoria: "Nel Tempo Libero" },
    // ── USI E COSTUMI ────────────────────────────────────────────────────────
    { frase: "IL MATRIMONIO TRADIZIONALE ITALIANO", categoria: "Usi e Costumi" },
    { frase: "I FUOCHI D ARTIFICIO DI FERRAGOSTO", categoria: "Usi e Costumi" },
    { frase: "LA PROCESSIONE DEL VENERDI SANTO", categoria: "Usi e Costumi" },
    { frase: "IL PALIO DI SIENA CON I CAVALLI", categoria: "Usi e Costumi" },
    { frase: "LA GITA FUORI PORTA DEL LUNEDI", categoria: "Usi e Costumi" },
    { frase: "LA SETTIMANA SANTA IN PROCIDA", categoria: "Usi e Costumi" },
    { frase: "IL TORNEO DI CALCETTO TRA COLLEGHI", categoria: "Usi e Costumi" },
    { frase: "LA MESSA DI MEZZANOTTE A NATALE", categoria: "Usi e Costumi" },
    { frase: "IL PRANZO DI PASQUA CON LE UOVA", categoria: "Usi e Costumi" },
    { frase: "LA COLOMBA E IL DOLCE DI PASQUA", categoria: "Usi e Costumi" },
    { frase: "IL VIN BRULE AI MERCATINI DI NATALE", categoria: "Usi e Costumi" },
    { frase: "LE CALZE DELLA BEFANA IL SEI GENNAIO", categoria: "Usi e Costumi" },
    { frase: "IL VOLO DELLA COLOMBA A FIRENZE", categoria: "Usi e Costumi" },
    { frase: "IL GIOSTRIERE DELLA QUINTANA", categoria: "Usi e Costumi" },
    { frase: "LA FESTA DI SAN GENNARO A NAPOLI", categoria: "Usi e Costumi" },
    { frase: "LA FIERA DI SANT AMBROGIO A MILANO", categoria: "Usi e Costumi" },
    { frase: "L ALBA DEL PRIMO DELL ANNO IN PIAZZA", categoria: "Usi e Costumi" },
    { frase: "IL PRIMO BAGNO IN MARE A GIUGNO", categoria: "Usi e Costumi" },
    { frase: "LA RACCOLTA DELLE OLIVE IN OTTOBRE", categoria: "Usi e Costumi" },
    { frase: "LA MACELLAZIONE DEL MAIALE IN INVERNO", categoria: "Usi e Costumi" },
    { frase: "LA CONSERVA DI POMODORO IN ESTATE", categoria: "Usi e Costumi" },
    { frase: "LA CRESIMA E LA PRIMA COMUNIONE", categoria: "Usi e Costumi" },
    { frase: "LA LAUREA CON LA CORONA DI ALLORO", categoria: "Usi e Costumi" },
    { frase: "IL COMPLEANNO CON LA TORTA E LE CANDELINE", categoria: "Usi e Costumi" },
    { frase: "LA PENSIONE CON LA FESTA DEI COLLEGHI", categoria: "Usi e Costumi" },
    { frase: "IL FUNERALE CON I FIORI BIANCHI", categoria: "Usi e Costumi" },
    // ── NATURA E AMBIENTE ────────────────────────────────────────────────────────
    { frase: "LA FORESTA AMAZZONICA IN PERICOLO", categoria: "Natura e Ambiente" },
    { frase: "LE ENERGIE RINNOVABILI PER IL FUTURO", categoria: "Natura e Ambiente" },
    { frase: "IL MARE MINACCIATO DALLA PLASTICA", categoria: "Natura e Ambiente" },
    { frase: "I GHIACCIAI SI STANNO SCIOGLIENDO", categoria: "Natura e Ambiente" },
    { frase: "LA FORESTA PLUVIALE OSPITA MILIONI", categoria: "Natura e Ambiente" },
    { frase: "IL PARCO NAZIONALE DEL GRAN PARADISO", categoria: "Natura e Ambiente" },
    { frase: "LA BIODIVERSITA DEL MEDITERRANEO", categoria: "Natura e Ambiente" },
    { frase: "IL VULCANO ETNA SULL ISOLA SICILIA", categoria: "Natura e Ambiente" },
    { frase: "I TERREMOTI SCUOTONO LA TERRA", categoria: "Natura e Ambiente" },
    { frase: "LA PRIMAVERA PORTA I FIORI NEI CAMPI", categoria: "Natura e Ambiente" },
    { frase: "IL DELTA DEL PO RISERVA NATURALE", categoria: "Natura e Ambiente" },
    { frase: "IL BOSCO IN AUTUNNO SI TINGE DI ROSSO", categoria: "Natura e Ambiente" },
    { frase: "L AURORA BOREALE NEI CIELI DEL NORD", categoria: "Natura e Ambiente" },
    { frase: "IL MONTE VESUVIO SOPRA NAPOLI", categoria: "Natura e Ambiente" },
    { frase: "LA PIOGGIA ACIDA DANNEGGIA I BOSCHI", categoria: "Natura e Ambiente" },
    { frase: "IL VENTO SCIROCCO DAL NORD AFRICA", categoria: "Natura e Ambiente" },
    { frase: "LA NEVE IN MONTAGNA IN INVERNO", categoria: "Natura e Ambiente" },
    { frase: "IL LAGO COME SPECCHIO DEL CIELO", categoria: "Natura e Ambiente" },
    { frase: "LA TEMPESTA TROPICALE NELL OCEANO", categoria: "Natura e Ambiente" },
    { frase: "IL PARCO NAZIONALE DELLE CINQUE TERRE", categoria: "Natura e Ambiente" },
    { frase: "IL MARE TIRRENO A OVEST D ITALIA", categoria: "Natura e Ambiente" },
    { frase: "L ADRIATICO A EST DELLA PENISOLA", categoria: "Natura e Ambiente" },
    { frase: "IL VULCANO STROMBOLI IN ERUZIONE", categoria: "Natura e Ambiente" },
    { frase: "LE DOLOMITI PATRIMONIO UNESCO", categoria: "Natura e Ambiente" },
    { frase: "LE ALPI PROTEGGONO IL NORD ITALIA", categoria: "Natura e Ambiente" },
    { frase: "GLI APPENNINI ATTRAVERSANO LA PENISOLA", categoria: "Natura e Ambiente" },
    { frase: "LO STRETTO DI MESSINA TRA SICILIA", categoria: "Natura e Ambiente" },
    { frase: "LA MAREMMA TOSCANA E SELVAGGIA", categoria: "Natura e Ambiente" },
    { frase: "IL BOSCO DI BETULLE IN AUTUNNO", categoria: "Natura e Ambiente" },
    { frase: "IL SUOLO FERTILE NUTRE I CAMPI", categoria: "Natura e Ambiente" },
    { frase: "L ACQUA DOLCE RISORSA PREZZIOSA", categoria: "Natura e Ambiente" },
    { frase: "LA SICCITA COLPISCE IL MERIDIONE", categoria: "Natura e Ambiente" },
    { frase: "LE INONDAZIONI DEVASTANO I PAESI", categoria: "Natura e Ambiente" },
    { frase: "IL TORNADO NEL CENTRO AMERICA", categoria: "Natura e Ambiente" },
    // ── SPETTACOLO ────────────────────────────────────────────────────────
    { frase: "IL TEATRO ALLA SCALA DI MILANO", categoria: "Spettacolo" },
    { frase: "SANREMO LA NOTTE DELLA MUSICA", categoria: "Spettacolo" },
    { frase: "LA COMMEDIA DELL ARTE ITALIANA", categoria: "Spettacolo" },
    { frase: "FIORELLO RE DELLO SPETTACOLO", categoria: "Spettacolo" },
    { frase: "MAURIZIO CROZZA E I SUOI PERSONAGGI", categoria: "Spettacolo" },
    { frase: "CORRADO GUZZANTI COMICO ITALIANO", categoria: "Spettacolo" },
    { frase: "RAFFAELLA CARRA ICONA TELEVISIVA", categoria: "Spettacolo" },
    { frase: "ZELIG IL TEATRO DELLA COMICITA", categoria: "Spettacolo" },
    { frase: "RENZO ARBORE E IL JAZZ ITALIANO", categoria: "Spettacolo" },
    { frase: "CARLO VERDONE REGISTA E ATTORE", categoria: "Spettacolo" },
    { frase: "DARIO FO PREMIO NOBEL PER IL TEATRO", categoria: "Spettacolo" },
    { frase: "PAOLO SORRENTINO REGISTA NAPOLETANO", categoria: "Spettacolo" },
    { frase: "LA PRIMA DELLA SCALA IL SETTE DICEMBRE", categoria: "Spettacolo" },
    { frase: "CLAUDIO BISIO ATTORE E COMICO", categoria: "Spettacolo" },
    { frase: "LUCA ZINGARETTI E MONTALBANO", categoria: "Spettacolo" },
    { frase: "IL COMMISSARIO MONTALBANO IN TV", categoria: "Spettacolo" },
    { frase: "CHECCO ZALONE IL COMICO DI CAPURSO", categoria: "Spettacolo" },
    { frase: "PANARIELLO IL COMICO TOSCANO", categoria: "Spettacolo" },
    { frase: "ANDREA CAMILLERI LO SCRITTORE", categoria: "Spettacolo" },
    { frase: "IL TEATRO DI STREHLER A MILANO", categoria: "Spettacolo" },
    // ── STORIA ────────────────────────────────────────────────────────
    { frase: "GIULIO CESARE IL DITTATORE DI ROMA", categoria: "Storia" },
    { frase: "MARCO POLO VIAGGIATORE VENEZIANO", categoria: "Storia" },
    { frase: "LA DICHIARAZIONE DI INDIPENDENZA AMERICANA", categoria: "Storia" },
    { frase: "I LANZICHENECCHI DEVASTANO L ITALIA", categoria: "Storia" },
    { frase: "L ASSEDIO DI TROIA DURO DIECI ANNI", categoria: "Storia" },
    { frase: "LA COSTRUZIONE DELLE PIRAMIDI", categoria: "Storia" },
    { frase: "AMERIGO VESPUCCI NAVIGATORE FIORENTINO", categoria: "Storia" },
    // ── PROVERBI E MODI DI DIRE ────────────────────────────────────────────────────────
    { frase: "TUTTE LE STRADE PORTANO A ROMA", categoria: "Proverbi e Modi di Dire" },
    { frase: "MEGLIO UN UOVO OGGI CHE UNA GALLINA DOMANI", categoria: "Proverbi e Modi di Dire" },
    { frase: "A CAVAL DONATO NON SI GUARDA IN BOCCA", categoria: "Proverbi e Modi di Dire" },
    { frase: "IL BUONGIORNO SI VEDE DAL MATTINO", categoria: "Proverbi e Modi di Dire" },
    { frase: "TANTO VA LA GATTA AL LARDO CHE CI LASCIA LO ZAMPINO", categoria: "Proverbi e Modi di Dire" },
    { frase: "AVERE IL COLTELLO DALLA PARTE DEL MANICO", categoria: "Proverbi e Modi di Dire" },
    { frase: "DI NOTTE TUTTI I GATTI SONO BIGI", categoria: "Proverbi e Modi di Dire" },
    // ── LIBRI ────────────────────────────────────────────────────────
    { frase: "IL VECCHIO E IL MARE DI HEMINGWAY", categoria: "Libri" },
    { frase: "DELITTO E CASTIGO DI DOSTOEVSKIJ", categoria: "Libri" },
    { frase: "IL SIGNORE DEGLI ANELLI DI TOLKIEN", categoria: "Libri" },
    { frase: "IL PICCOLO PRINCIPE DI SAINT EXUPERY", categoria: "Libri" },
    { frase: "ORGOGLIO E PREGIUDIZIO DI AUSTEN", categoria: "Libri" },
    { frase: "CENT ANNI DI SOLITUDINE DI GARCIA MARQUEZ", categoria: "Libri" },
    // ── CINEMA E ATTORI ────────────────────────────────────────────────────────
    { frase: "FEDERICO FELLINI MAESTRO DEL CINEMA", categoria: "Cinema e Attori" },
    { frase: "TITANIC CON LEONARDO DICAPRIO", categoria: "Cinema e Attori" },
    { frase: "STAR WARS LA GUERRA DELLE STELLE", categoria: "Cinema e Attori" },
    { frase: "INDIANA JONES E IL TEMPIO MALEDETTO", categoria: "Cinema e Attori" },
    { frase: "CLINT EASTWOOD IL BUONO IL BRUTTO IL CATTIVO", categoria: "Cinema e Attori" },
    { frase: "ALBERTO SORDI ICONA DEL CINEMA ITALIANO", categoria: "Cinema e Attori" },
    { frase: "MARCELLO MASTROIANNI IL DIVO", categoria: "Cinema e Attori" },
    { frase: "MONICA VITTI E IL CINEMA D AUTORE", categoria: "Cinema e Attori" },
    { frase: "VITTORIO GASSMAN IL MATTATORE", categoria: "Cinema e Attori" },
    { frase: "ROBERTO BENIGNI LA VITA E BELLA", categoria: "Cinema e Attori" },
    { frase: "TOTÒ IL PRINCIPE DELLA RISATA", categoria: "Cinema e Attori" },
    { frase: "INTERSTELLAR DI CHRISTOPHER NOLAN", categoria: "Cinema e Attori" },
    // ── MUSICA ────────────────────────────────────────────────────────
    { frase: "MOZART COMPOSITORE PRODIGIO", categoria: "Musica" },
    { frase: "BOB DYLAN CANTAUTORE PREMIO NOBEL", categoria: "Musica" },
    { frase: "JIMI HENDRIX LA CHITARRA CHE BRUCIA", categoria: "Musica" },
    { frase: "ARETHA FRANKLIN LA REGINA DEL SOUL", categoria: "Musica" },
    { frase: "ANDREA BOCELLI TENORE TOSCANO", categoria: "Musica" },
    { frase: "DOMENICO MODUGNO NEL BLU DIPINTO DI BLU", categoria: "Musica" },
    { frase: "LUCIO BATTISTI IL MITO ITALIANO", categoria: "Musica" },
    { frase: "VASCO ROSSI IL BLASCO DI ZOCCA", categoria: "Musica" },
    { frase: "ZUCCHERO FORNACIARI BLUES ITALIANO", categoria: "Musica" },
    { frase: "CLAUDIO BAGLIONI UN CANTAUTORE ROMANO", categoria: "Musica" },
    { frase: "SANREMO IL FESTIVAL DELLA CANZONE ITALIANA", categoria: "Musica" },
    // ── ASTRONOMIA ────────────────────────────────────────────────────────
    { frase: "SATURNO IL PIANETA CON GLI ANELLI", categoria: "Astronomia" },
    { frase: "MERCURIO IL PIANETA PIU PICCOLO", categoria: "Astronomia" },
    { frase: "LA LUNA SI FORMA DOPO UN IMPATTO", categoria: "Astronomia" },
    { frase: "LA LUNA PIENA OGNI VENTOTTO GIORNI", categoria: "Astronomia" },
    { frase: "IL TELESCOPIO DI HUBBLE NELLO SPAZIO", categoria: "Astronomia" },
    { frase: "LE STELLE CADENTI SONO METEORE", categoria: "Astronomia" },
    { frase: "UN ANNO LUCE E UNA DISTANZA ENORME", categoria: "Astronomia" },
    { frase: "LE COSTELLAZIONI DEL CIELO BOREALE", categoria: "Astronomia" },
    { frase: "YURI GAGARIN PRIMO UOMO NELLO SPAZIO", categoria: "Astronomia" },
    { frase: "NEIL ARMSTRONG SULLA LUNA NEL 1969", categoria: "Astronomia" },
    { frase: "UNA SUPERNOVA ESPLODE ALLA FINE", categoria: "Astronomia" },
    { frase: "IL BUCO NERO INGHIOTTE LA LUCE", categoria: "Astronomia" },
    { frase: "IL BIG BANG ORIGINE DELL UNIVERSO", categoria: "Astronomia" },
    { frase: "LE GALASSIE SI ALLONTANANO TRA LORO", categoria: "Astronomia" },
    // ── INVENZIONI ────────────────────────────────────────────────────────
    { frase: "LA STAMPA A CARATTERI MOBILI DI GUTENBERG", categoria: "Invenzioni" },
    { frase: "LA RUOTA LA PRIMA GRANDE INVENZIONE", categoria: "Invenzioni" },
    { frase: "LA LAMPADINA INVENTATA DA EDISON", categoria: "Invenzioni" },
    { frase: "IL TELEFONO INVENTATO DA BELL", categoria: "Invenzioni" },
    { frase: "LA RADIO DI GUGLIELMO MARCONI", categoria: "Invenzioni" },
    { frase: "IL COMPUTER IL CERVELLO ELETTRONICO", categoria: "Invenzioni" },
    { frase: "INTERNET LA RETE CHE CONNETTE IL MONDO", categoria: "Invenzioni" },
    { frase: "LO SMARTPHONE TUTTO IN UN DISPOSITIVO", categoria: "Invenzioni" },
    { frase: "IL VACCINO SALVA MILIONI DI VITE", categoria: "Invenzioni" },
    { frase: "L AEROPLANO DEI FRATELLI WRIGHT", categoria: "Invenzioni" },
    { frase: "IL MOTORE A REAZIONE SPINGE L AEREO", categoria: "Invenzioni" },
    { frase: "LA BOMBA ATOMICA PROGETTO MANHATTAN", categoria: "Invenzioni" },
    { frase: "LA MACCHINA A VAPORE CAMBIA IL MONDO", categoria: "Invenzioni" },
    { frase: "IL MICROSCOPIO RIVELA IL MONDO PICCOLO", categoria: "Invenzioni" },
    { frase: "IL CINEMA DEI FRATELLI LUMIERE", categoria: "Invenzioni" },
    { frase: "IL FRIGORIFERO CONSERVA IL CIBO", categoria: "Invenzioni" },
    // ── GEOGRAFIA E VIAGGI ────────────────────────────────────────────────────────
    { frase: "IL SAHARA IL DESERTO PIU GRANDE", categoria: "Geografia e Viaggi" },
    { frase: "IL GRANDE CANYON SCAVATO DAL COLORADO", categoria: "Geografia e Viaggi" },
    { frase: "IL MONTE BIANCO TETTO D EUROPA", categoria: "Geografia e Viaggi" },
    { frase: "IL LAGO TITICACA IN SUDAMERICA", categoria: "Geografia e Viaggi" },
    { frase: "IL PORTO DI SYDNEY IN AUSTRALIA", categoria: "Geografia e Viaggi" },
    { frase: "IL CANALE DI SUEZ UNISCE I MARI", categoria: "Geografia e Viaggi" },
    { frase: "IL CANALE DI PANAMA TRA ATLANTICO E PACIFICO", categoria: "Geografia e Viaggi" },
    { frase: "LA MURAGLIA CINESE VISIBILE DALLO SPAZIO", categoria: "Geografia e Viaggi" },
    { frase: "LE PIRAMIDI DI GIZA NEL DESERTO", categoria: "Geografia e Viaggi" },
    { frase: "IL COLOSSEO DI ROMA MARAVIGLIA DEL MONDO", categoria: "Geografia e Viaggi" },
    // ── IN CUCINA ────────────────────────────────────────────────────────
    { frase: "LA PIZZA MARGHERITA CON POMODORO E MOZZARELLA", categoria: "In Cucina" },
    { frase: "LA PASTA ALLA CARBONARA ROMANA", categoria: "In Cucina" },
    { frase: "IL RISOTTO ALLO ZAFFERANO MILANESE", categoria: "In Cucina" },
    { frase: "LE LASAGNE AL FORNO CON BESCIAMELLA", categoria: "In Cucina" },
    { frase: "IL TIRAMISÙ DOLCE AL MASCARPONE", categoria: "In Cucina" },
    { frase: "LA PANNA COTTA CON FRUTTI DI BOSCO", categoria: "In Cucina" },
    { frase: "IL BRODETTO DI PESCE DELL ADRIATICO", categoria: "In Cucina" },
    { frase: "IL RAGÙ BOLOGNESE SULLE TAGLIATELLE", categoria: "In Cucina" },
    { frase: "LE ORECCHIETTE CON LE CIME DI RAPA", categoria: "In Cucina" },
    { frase: "IL CANNOLO SICILIANO CON RICOTTA", categoria: "In Cucina" },
    { frase: "LA FOCACCIA GENOVESE ALL OLIO", categoria: "In Cucina" },
    { frase: "IL PARMIGIANO REGGIANO IL RE DEI FORMAGGI", categoria: "In Cucina" },
    { frase: "L ESPRESSO ITALIANO RISTRETTO", categoria: "In Cucina" },
    { frase: "LA MOZZARELLA DI BUFALA CAMPANA", categoria: "In Cucina" },
    // ── ANIMALI ────────────────────────────────────────────────────────
    { frase: "LA GIRAFFA CON IL COLLO LUNGHISSIMO", categoria: "Animali" },
    { frase: "IL GHEPARDO L ANIMALE PIU VELOCE", categoria: "Animali" },
    { frase: "IL DELFINO INTELLIGENTE NEL MARE", categoria: "Animali" },
    { frase: "LA BALENA BLU IL MAMMIFERO PIU GRANDE", categoria: "Animali" },
    { frase: "IL COCCODRILLO GUARDIANO DEL NILO", categoria: "Animali" },
    { frase: "IL PANDA GIGANTE IN VIA DI ESTINZIONE", categoria: "Animali" },
    { frase: "IL KOALA DORMEtre QUATTORDICI ORE AL GIORNO", categoria: "Animali" },
    { frase: "LA FARFALLA MONARCHA MIGRA IN AMERICA", categoria: "Animali" },
    { frase: "IL GORILLA IL PIU GRANDE PRIMATE", categoria: "Animali" },
    { frase: "IL LUPO GRIGIO CACCIATORE DI BRANCO", categoria: "Animali" },
    { frase: "IL CORVO UCCELLO INTELLIGENTE", categoria: "Animali" },
    { frase: "IL PAPPAGALLO IMITA LA VOCE UMANA", categoria: "Animali" },
    { frase: "IL SERPENTE A SONAGLI NEL DESERTO", categoria: "Animali" },
    { frase: "L ELEFANTE HA UNA MEMORIA PRODIGIOSA", categoria: "Animali" },
    { frase: "IL RINOCERONTE IN PERICOLO DI ESTINZIONE", categoria: "Animali" },
    // ── NELLO SPORT ────────────────────────────────────────────────────────
    { frase: "RAFAEL NADAL IL TORO DI MANACOR", categoria: "Nello Sport" },
    { frase: "NOVAK DJOKOVIC NUMERO UNO AL MONDO", categoria: "Nello Sport" },
    { frase: "MIKE TYSON IL PIU GIOVANE CAMPIONE", categoria: "Nello Sport" },
    { frase: "MICHAEL PHELPS OLIMPIADI D ORO", categoria: "Nello Sport" },
    { frase: "NADIA COMANECI IL DIECI PERFETTO", categoria: "Nello Sport" },
    { frase: "CARL LEWIS QUATTRO ORO A LOS ANGELES", categoria: "Nello Sport" },
    { frase: "USAIN BOLT IL FULMINE DI GIAMAICA", categoria: "Nello Sport" },
    { frase: "MICHAEL JORDAN IL DIO DEL BASKET", categoria: "Nello Sport" },
    { frase: "VALENTINO ROSSI IL DOTTOR SIMPATIA", categoria: "Nello Sport" },
    { frase: "AYRTON SENNA CAMPIONE DI FORMULA UNO", categoria: "Nello Sport" },
    { frase: "MICHAEL SCHUMACHER SETTE TITOLI MONDIALI", categoria: "Nello Sport" },
    { frase: "ROGER MILLA I MONDIALI DI ITALIA 90", categoria: "Nello Sport" },
    { frase: "GIGI BUFFON IL PORTIERE DI ITALIA", categoria: "Nello Sport" },
    { frase: "ANDREA PIRLO IL MAESTRO DEL CALCIO", categoria: "Nello Sport" },
    { frase: "GIORGIO ARMANI DEL CALCIO MONDIALE", categoria: "Nello Sport" },
    { frase: "I MONDIALI DI CALCIO IN SUDAFRICA", categoria: "Nello Sport" },
    { frase: "LA MARATONA DI BERLINO RECORD MONDIALE", categoria: "Nello Sport" },
    // ── NEL TEMPO LIBERO ────────────────────────────────────────────────────────
    { frase: "LA GITA IN BICICLETTA IN CAMPAGNA", categoria: "Nel Tempo Libero" },
    { frase: "UN FILM AL CINEMA CON GLI AMICI", categoria: "Nel Tempo Libero" },
    { frase: "LA PARTITA DI SCACCHI CON IL NONNO", categoria: "Nel Tempo Libero" },
    { frase: "UN CONCERTO DI MUSICA DAL VIVO", categoria: "Nel Tempo Libero" },
    { frase: "LA VISITA AL MUSEO D ARTE MODERNA", categoria: "Nel Tempo Libero" },
    { frase: "UNA SERATA DI TEATRO IN PIAZZA", categoria: "Nel Tempo Libero" },
    { frase: "LA PESCA CON LA CANNA AL LAGHETTO", categoria: "Nel Tempo Libero" },
    { frase: "UN WEEKEND DI TREKKING IN MONTAGNA", categoria: "Nel Tempo Libero" },
    { frase: "LA CENA CON GLI AMICI DI VECCHIA DATA", categoria: "Nel Tempo Libero" },
    { frase: "IL CORSO DI FOTOGRAFIA DIGITALE", categoria: "Nel Tempo Libero" },
    { frase: "LA PARTITA DI PALLACANESTRO AL CAMPETTO", categoria: "Nel Tempo Libero" },
    { frase: "UNA GIORNATA AL MARE FUORI STAGIONE", categoria: "Nel Tempo Libero" },
    { frase: "IL PICNIC NEL PARCO DI PRIMAVERA", categoria: "Nel Tempo Libero" },
    { frase: "LA PARTITA DI BOCCE AL CIRCOLO", categoria: "Nel Tempo Libero" },
    { frase: "UN VIAGGIO IN TRENO SENZA META", categoria: "Nel Tempo Libero" },
    { frase: "LA RACCOLTA DEI FUNGHI NEL BOSCO", categoria: "Nel Tempo Libero" },
    { frase: "UN POMERIGGIO A DIPINGERE ACQUERELLI", categoria: "Nel Tempo Libero" },
    // ── USI E COSTUMI ────────────────────────────────────────────────────────
    { frase: "IL CARNEVALE DI VENEZIA LE MASCHERE", categoria: "Usi e Costumi" },
    { frase: "LA SAGRA DEL TARTUFO IN UMBRIA", categoria: "Usi e Costumi" },
    { frase: "IL PALIO DI SIENA IN PIAZZA DEL CAMPO", categoria: "Usi e Costumi" },
    { frase: "LA BEFANA PORTA I DONI IL SEI GENNAIO", categoria: "Usi e Costumi" },
    { frase: "LA GIOSTRA DEL SARACINO AD AREZZO", categoria: "Usi e Costumi" },
    { frase: "IL CALCIO STORICO FIORENTINO", categoria: "Usi e Costumi" },
    { frase: "IL BACIO IN BOCCA AL MATRIMONIO", categoria: "Usi e Costumi" },
    { frase: "LA PRIMA COMUNIONE DEI BAMBINI", categoria: "Usi e Costumi" },
    { frase: "IL BATTESIMO DEL BAMBINO APPENA NATO", categoria: "Usi e Costumi" },
    { frase: "LA TRADIZIONE DEL PANDORO A NATALE", categoria: "Usi e Costumi" },
    { frase: "LA COTTURA DEL MAIALE A SAN MARTINO", categoria: "Usi e Costumi" },
    { frase: "LA CACCIA AL TARTUFO CON I CANI", categoria: "Usi e Costumi" },
    { frase: "IL MERCATINO DI NATALE IN ALTO ADIGE", categoria: "Usi e Costumi" },
    { frase: "LA CAMORRA LA MAFIA E L NDRANGHETA", categoria: "Usi e Costumi" },
    { frase: "IL RITO DELLA PASTA FATTA IN CASA", categoria: "Usi e Costumi" },
    // ── NATURA E AMBIENTE ────────────────────────────────────────────────────────
    { frase: "LA FORESTA PLUVIALE AMAZONICA", categoria: "Natura e Ambiente" },
    { frase: "IL CAMBIAMENTO CLIMATICO SFIDA GLOBALE", categoria: "Natura e Ambiente" },
    { frase: "LE ENERGIE RINNOVABILI IL FUTURO", categoria: "Natura e Ambiente" },
    { frase: "IL VENTO MUOVE LE TURBINE EOLICHE", categoria: "Natura e Ambiente" },
    { frase: "IL TERREMOTO CHE SCUOTE LA TERRA", categoria: "Natura e Ambiente" },
    { frase: "L INONDAZIONE TRAVOLGE I CAMPI", categoria: "Natura e Ambiente" },
    { frase: "IL TRAMONTO SULL OCEANO ATLANTICO", categoria: "Natura e Ambiente" },
    { frase: "IL GHIACCIAIO DEL FRANZ JOSEF", categoria: "Natura e Ambiente" },
    { frase: "IL DELTA DEL PO PATRIMONIO UNESCO", categoria: "Natura e Ambiente" },
    { frase: "LA MAREMMA TOSCANA SELVATICA", categoria: "Natura e Ambiente" },
    { frase: "IL POLLINO IL PIU GRANDE PARCO D ITALIA", categoria: "Natura e Ambiente" },
    // ── SPETTACOLO ────────────────────────────────────────────────────────
    { frase: "UN POSTO AL SOLE LA SOAP ITALIANA", categoria: "Spettacolo" },
    { frase: "IL GRANDE FRATELLO IL REALITY", categoria: "Spettacolo" },
    { frase: "UOMINI E DONNE DI MARIA DE FILIPPI", categoria: "Spettacolo" },
    { frase: "STRISCIA LA NOTIZIA IL TG SATIRICO", categoria: "Spettacolo" },
    { frase: "REPORT IL PROGRAMMA DI INCHIESTE", categoria: "Spettacolo" },
    { frase: "QUARTO GRADO I GIALLI IRRISOLTI", categoria: "Spettacolo" },
    { frase: "REAZIONE A CATENA ESTATE IN TV", categoria: "Spettacolo" },
    { frase: "AFFARI TUOI IL GIOCO DEI PACCHI", categoria: "Spettacolo" },
    { frase: "IL FESTIVAL DI CANNES PALMA D ORO", categoria: "Spettacolo" },
    { frase: "LA NOTTE DEGLI OSCAR A HOLLYWOOD", categoria: "Spettacolo" },
    { frase: "IL GOLDEN GLOBE PREMIA IL CINEMA", categoria: "Spettacolo" },
    { frase: "IL PREMIO NOBEL PER LA LETTERATURA", categoria: "Spettacolo" },
    { frase: "IL DAVID DI DONATELLO CINEMA ITALIANO", categoria: "Spettacolo" },
    { frase: "LA MOSTRA DEL CINEMA DI VENEZIA", categoria: "Spettacolo" },
    { frase: "IL PREMIO STREGA IL MEGLIO DEI ROMANZI", categoria: "Spettacolo" },
    { frase: "IL CIRCO TOGNI SOTTO IL TENDONE", categoria: "Spettacolo" },
    // ── ANATOMIA ────────────────────────────────────────────────────────
    { frase: "IL CUORE BATTE SETTANTA VOLTE", categoria: "Anatomia" },
    { frase: "LE PIASTRINE E LA COAGULAZIONE", categoria: "Anatomia" },
    // ── ARTE E PITTURA ────────────────────────────────────────────────────────
    { frase: "LA PERSISTENZA DELLA MEMORIA", categoria: "Arte e Pittura" },
    { frase: "LE PORTE DEL PARADISO DI GHIBERTI", categoria: "Arte e Pittura" },
    { frase: "L ERMITAGE DI SAN PIETROBURGO", categoria: "Arte e Pittura" },
    { frase: "LA PROSPETTIVA RINASCIMENTALE", categoria: "Arte e Pittura" },
    { frase: "IL RESTAURO DELLE OPERE D ARTE", categoria: "Arte e Pittura" },
    // ── TECNOLOGIA ────────────────────────────────────────────────────────
    { frase: "IL LINGUAGGIO DI PROGRAMMAZIONE", categoria: "Tecnologia" },
    { frase: "IL VISORE PER REALTA VIRTUALE", categoria: "Tecnologia" },
    { frase: "LA TOMOGRAFIA COMPUTERIZZATA", categoria: "Tecnologia" },
    { frase: "LA REALTÀ DEL GEMELLO DIGITALE", categoria: "Tecnologia" },
    // ── CURIOSITÀ DAL MONDO ────────────────────────────────────────────────────────
    { frase: "LA BARRIERA CORALLINA AUSTRALIANA", categoria: "Curiosità dal Mondo" },
    { frase: "IL GHIACCIAIO CHE SI SCIOGLIE", categoria: "Curiosità dal Mondo" },
    { frase: "IL PUNTO PIU PROFONDO DELL OCEANO", categoria: "Curiosità dal Mondo" },
    { frase: "LE STALATTITI E LE STALAGMITI", categoria: "Curiosità dal Mondo" },
    { frase: "IL PAESE PIU PICCOLO DEL MONDO", categoria: "Curiosità dal Mondo" },
    // ── SINONIMI E CONTRARI ────────────────────────────────────────────────────────
    { frase: "IL CONTRARIO DI FELICE SI DICE TRISTE", categoria: "Sinonimi e Contrari" },
    { frase: "VELOCE E RAPIDO HANNO LO STESSO SENSO", categoria: "Sinonimi e Contrari" },
    { frase: "GRANDE E PICCOLO SONO DUE CONTRARI", categoria: "Sinonimi e Contrari" },
    { frase: "CALDO E FREDDO SONO PAROLE OPPOSTE", categoria: "Sinonimi e Contrari" },
    { frase: "BELLO E BRUTTO SI ESCLUDONO TRA LORO", categoria: "Sinonimi e Contrari" },
    { frase: "CORAGGIOSO E SINONIMO DI VALOROSO", categoria: "Sinonimi e Contrari" },
    { frase: "ANTICO E MODERNO SONO OPPOSTI NETTI", categoria: "Sinonimi e Contrari" },
    { frase: "GENTILE E IL CONTRARIO DI SCORTESE", categoria: "Sinonimi e Contrari" },
    { frase: "FORTE E DEBOLE ESPRIMONO FORZE DIVERSE", categoria: "Sinonimi e Contrari" },
    { frase: "RICCO E POVERO DEFINISCONO LA RICCHEZZA", categoria: "Sinonimi e Contrari" },
    { frase: "ONESTO E DISONESTO SONO OPPOSTI MORALI", categoria: "Sinonimi e Contrari" },
    { frase: "SILENZIOSO E IL CONTRARIO DI RUMOROSO", categoria: "Sinonimi e Contrari" },
    { frase: "PAZIENTE HA IL CONTRARIO IN IMPAZIENTE", categoria: "Sinonimi e Contrari" },
    { frase: "DOLCE E AMARO DESCRIVONO DUE SAPORI", categoria: "Sinonimi e Contrari" },
    { frase: "OTTIMISTA SI CONTRAPPONE A PESSIMISTA", categoria: "Sinonimi e Contrari" },
    { frase: "UMILE E ARROGANTE SONO OPPOSTI CHIARI", categoria: "Sinonimi e Contrari" },
    { frase: "PULITO E IL CONTRARIO NETTO DI SPORCO", categoria: "Sinonimi e Contrari" },
    { frase: "FACILE HA COME CONTRARIO DIFFICILE", categoria: "Sinonimi e Contrari" },
    { frase: "COSTRUIRE E DEMOLIRE SONO AZIONI OPPOSTE", categoria: "Sinonimi e Contrari" },
    { frase: "SALIRE E SCENDERE VANNO IN DIREZIONI INVERSE", categoria: "Sinonimi e Contrari" },
    { frase: "PIENO E VUOTO SONO DUE STATI CONTRARI", categoria: "Sinonimi e Contrari" },
    { frase: "VERO E FALSO SONO CONCETTI OPPOSTI", categoria: "Sinonimi e Contrari" },
    { frase: "AMICO E NEMICO SONO RUOLI CONTRARI", categoria: "Sinonimi e Contrari" },
    { frase: "GIOIA E DOLORE SONO SENTIMENTI OPPOSTI", categoria: "Sinonimi e Contrari" },
    { frase: "SPERANZA E DISPERAZIONE SI CONTRAPPONGONO", categoria: "Sinonimi e Contrari" },
    // ── ANATOMIA ────────────────────────────────────────────────────────
    { frase: "IL CUORE POMPA IL SANGUE NEL CORPO", categoria: "Anatomia" },
    { frase: "IL CERVELLO CONTROLLA TUTTE LE FUNZIONI", categoria: "Anatomia" },
    { frase: "I POLMONI SERVONO PER LA RESPIRAZIONE", categoria: "Anatomia" },
    { frase: "LO SCHELETRO E FORMATO DA DUECENTOSEI OSSA", categoria: "Anatomia" },
    { frase: "I RENI FILTRANO LE SOSTANZE DEL SANGUE", categoria: "Anatomia" },
    { frase: "IL FEGATO PRODUCE LA BILE PER DIGERIRE", categoria: "Anatomia" },
    { frase: "LA PELLE E IL PIU GRANDE ORGANO DEL CORPO", categoria: "Anatomia" },
    { frase: "I MUSCOLI SI CONTRAGGONO PER MUOVERSI", categoria: "Anatomia" },
    { frase: "IL MIDOLLO SPINALE TRASMETTE I SEGNALI", categoria: "Anatomia" },
    { frase: "LE ARTERIE PORTANO IL SANGUE DAL CUORE", categoria: "Anatomia" },
    { frase: "LA CORNEA E IL VETRO TRASPARENTE DELL OCCHIO", categoria: "Anatomia" },
    { frase: "I NEURONI SONO LE CELLULE DEL CERVELLO", categoria: "Anatomia" },
    { frase: "IL PANCREAS PRODUCE INSULINA E GLUCAGONE", categoria: "Anatomia" },
    { frase: "LO STOMACO DIGERISCE IL CIBO CON ACIDI", categoria: "Anatomia" },
    { frase: "L INTESTINO TENUE ASSORBE I NUTRIENTI", categoria: "Anatomia" },
    { frase: "LE OSSA DEL CRANIO PROTEGGONO IL CERVELLO", categoria: "Anatomia" },
    { frase: "IL TIMPANO VIBRA AI SUONI E AI RUMORI", categoria: "Anatomia" },
    { frase: "LA MILZA FILTRA I GLOBULI ROSSI VECCHI", categoria: "Anatomia" },
    { frase: "I TENDINI COLLEGANO I MUSCOLI ALLE OSSA", categoria: "Anatomia" },
    { frase: "LE VENE RIPORTANO IL SANGUE AL CUORE", categoria: "Anatomia" },
    { frase: "IL DIAFRAMMA CONTROLLA IL RESPIRO", categoria: "Anatomia" },
    { frase: "L APPENDICE E UN ORGANO VESTIGIALE", categoria: "Anatomia" },
    { frase: "LE GHIANDOLE SURRENALI PRODUCONO ADRENALINA", categoria: "Anatomia" },
    { frase: "LA TIROIDE REGOLA IL METABOLISMO DEL CORPO", categoria: "Anatomia" },
    { frase: "IL GANGLIO E UN NODO DELLA RETE NERVOSA", categoria: "Anatomia" },
    // ── ARTE E PITTURA ────────────────────────────────────────────────────────
    { frase: "LA GIOCONDA DI LEONARDO DA VINCI SORRIDE", categoria: "Arte e Pittura" },
    { frase: "MICHELANGELO AFFRESCA LA VOLTA DELLA SISTINA", categoria: "Arte e Pittura" },
    { frase: "VAN GOGH DIPINGE LA NOTTE STELLATA", categoria: "Arte e Pittura" },
    { frase: "SALVADOR DALI INVENTA IL SURREALISMO", categoria: "Arte e Pittura" },
    { frase: "PABLO PICASSO FONDA IL CUBISMO MODERNO", categoria: "Arte e Pittura" },
    { frase: "CARAVAGGIO USA IL CHIAROSCURO NEI DIPINTI", categoria: "Arte e Pittura" },
    { frase: "BOTTICELLI DIPINGE LA NASCITA DI VENERE", categoria: "Arte e Pittura" },
    { frase: "RAFFAELLO DECORA LE STANZE IN VATICANO", categoria: "Arte e Pittura" },
    { frase: "REMBRANDT IL MAESTRO DELLA LUCE E OMBRA", categoria: "Arte e Pittura" },
    { frase: "MONET DIPINGE LE NINFEE NEL SUO GIARDINO", categoria: "Arte e Pittura" },
    { frase: "RENOIR RAPPRESENTA LA VITA PARIGINA", categoria: "Arte e Pittura" },
    { frase: "DEGAS RITRAE LE BALLERINE IN MOVIMENTO", categoria: "Arte e Pittura" },
    { frase: "GAUGUIN DIPINGE A TAHITI COLORI VIVACI", categoria: "Arte e Pittura" },
    { frase: "CEZANNE PRECURSORE DELL ARTE MODERNA", categoria: "Arte e Pittura" },
    { frase: "KLIMT DECORA CON ORO I SUOI CAPOLAVORI", categoria: "Arte e Pittura" },
    { frase: "MAGRITTE IL MAESTRO BELGA DEL SURREALE", categoria: "Arte e Pittura" },
    { frase: "WARHOL TRASFORMA I BARATTOLI IN ARTE", categoria: "Arte e Pittura" },
    { frase: "FRIDA KAHLO DIPINGE SE STESSA CON DOLORE", categoria: "Arte e Pittura" },
    { frase: "MONDRIAN RIDUCE LA PITTURA A LINEE E COLORI", categoria: "Arte e Pittura" },
    { frase: "KANDINSKY PADRE DELL ARTE ASTRATTA PURA", categoria: "Arte e Pittura" },
    { frase: "LA VENERE DI MILO E UNA SCULTURA GRECA", categoria: "Arte e Pittura" },
    { frase: "IL DAVID DI MICHELANGELO E A FIRENZE", categoria: "Arte e Pittura" },
    { frase: "TIZIANO IL GRANDE COLORISTA VENEZIANO", categoria: "Arte e Pittura" },
    { frase: "TINTORETTO DIPINGE VASTE TELE A VENEZIA", categoria: "Arte e Pittura" },
    { frase: "TIEPOLO AFFRESCA I SOFFITTI CON GLORIA", categoria: "Arte e Pittura" },
    // ── TECNOLOGIA ────────────────────────────────────────────────────────
    { frase: "L INTELLIGENZA ARTIFICIALE CAMBIA IL MONDO", categoria: "Tecnologia" },
    { frase: "IL COMPUTER QUANTISTICO CALCOLA PIU IN FRETTA", categoria: "Tecnologia" },
    { frase: "LA REALTA VIRTUALE IMMERGE IN MONDI DIGITALI", categoria: "Tecnologia" },
    { frase: "IL TELEFONO CELLULARE CONNETTE MILIARDI DI PERSONE", categoria: "Tecnologia" },
    { frase: "INTERNET DELLE COSE COLLEGA CASA E UFFICIO", categoria: "Tecnologia" },
    { frase: "LA STAMPA TRIDIMENSIONALE CREA OGGETTI SOLIDI", categoria: "Tecnologia" },
    { frase: "IL RICONOSCIMENTO FACCIALE SBLOCCA LO SMARTPHONE", categoria: "Tecnologia" },
    { frase: "IL CLOUD COMPUTING ARCHIVIA DATI IN REMOTO", categoria: "Tecnologia" },
    { frase: "I BIG DATA ANALIZZANO MILIARDI DI INFORMAZIONI", categoria: "Tecnologia" },
    { frase: "LA BLOCKCHAIN GARANTISCE TRANSAZIONI SICURE", categoria: "Tecnologia" },
    { frase: "IL VEICOLO ELETTRICO SOSTITUISCE LA BENZINA", categoria: "Tecnologia" },
    { frase: "IL PANNELLO SOLARE CONVERTE LUCE IN CORRENTE", categoria: "Tecnologia" },
    { frase: "LA TURBINA EOLICA PRODUCE ENERGIA DAL VENTO", categoria: "Tecnologia" },
    { frase: "IL ROBOT INDUSTRIALE ASSEMBLA LE AUTOMOBILI", categoria: "Tecnologia" },
    { frase: "LA CHIRURGIA ROBOTICA OPERA CON PRECISIONE", categoria: "Tecnologia" },
    { frase: "IL SATELLITE GPS INDICA LA POSIZIONE ESATTA", categoria: "Tecnologia" },
    { frase: "IL MICROPROCESSORE E IL CUORE DEL COMPUTER", categoria: "Tecnologia" },
    { frase: "LA RETE NEURALE ARTIFICIALE IMPARA DAI DATI", categoria: "Tecnologia" },
    { frase: "IL DRONE VOLA SENZA PILOTA A BORDO", categoria: "Tecnologia" },
    { frase: "LA MEMORIA FLASH CONSERVA I DATI SENZA CORRENTE", categoria: "Tecnologia" },
    { frase: "IL TOUCH SCREEN RISPONDE AL TOCCO DEL DITO", categoria: "Tecnologia" },
    { frase: "LO STREAMING TRASMETTE VIDEO IN TEMPO REALE", categoria: "Tecnologia" },
    { frase: "IL VISORE MISTO SOVRAPPONE DIGITALE E REALE", categoria: "Tecnologia" },
    { frase: "LA CRITTOGRAFIA PROTEGGE I MESSAGGI PRIVATI", categoria: "Tecnologia" },
    // ── CURIOSITÀ DAL MONDO ────────────────────────────────────────────────────────
    { frase: "LA LINGUA PIU PARLATA AL MONDO E IL CINESE", categoria: "Curiosità dal Mondo" },
    { frase: "IL MONTE EVEREST E IL PUNTO PIU ALTO DELLA TERRA", categoria: "Curiosità dal Mondo" },
    { frase: "LA FOSSA DELLE MARIANNE E LA PIU PROFONDA", categoria: "Curiosità dal Mondo" },
    { frase: "IL NILO E IL FIUME PIU LUNGO DEL MONDO", categoria: "Curiosità dal Mondo" },
    { frase: "LA FORESTA AMAZZONICA PRODUCE META DELL OSSIGENO", categoria: "Curiosità dal Mondo" },
    { frase: "IL DESERTO DEL SAHARA E IL PIU GRANDE AL MONDO", categoria: "Curiosità dal Mondo" },
    { frase: "LA BALENA BLU E IL PIU GRANDE ANIMALE VIVENTE", categoria: "Curiosità dal Mondo" },
    { frase: "LE API COMUNICANO ATTRAVERSO LA DANZA", categoria: "Curiosità dal Mondo" },
    { frase: "IL POLPO PUO CAMBIARE COLORE E FORMA", categoria: "Curiosità dal Mondo" },
    { frase: "I PIPISTRELLI SI ORIENTANO CON GLI ULTRASUONI", categoria: "Curiosità dal Mondo" },
    { frase: "IL COLIBRÌ BATTE LE ALI OTTANTA VOLTE AL SECONDO", categoria: "Curiosità dal Mondo" },
    { frase: "LA TARTARUGA GIGANTE PUO VIVERE PIU DI CENTO ANNI", categoria: "Curiosità dal Mondo" },
    { frase: "IL CAMALEONTE VEDE IN TUTTE LE DIREZIONI", categoria: "Curiosità dal Mondo" },
    { frase: "IL CALAMARO GIGANTE VIVE NEGLI ABISSI MARINI", categoria: "Curiosità dal Mondo" },
    { frase: "LA LUMACA LASCIA UNA SCIA DI MUCO APPICCICOSO", categoria: "Curiosità dal Mondo" },
    { frase: "IL GHIACCIAIO DELLA GROELANDIA SI STA SCIOGLIENDO", categoria: "Curiosità dal Mondo" },
    { frase: "L AURORA BOREALE ILLUMINA IL CIELO NORDICO", categoria: "Curiosità dal Mondo" },
    { frase: "IL VULCANO KILAUEA ERUTTA SENZA MAI FERMARSI", categoria: "Curiosità dal Mondo" },
    { frase: "LA GRANDE BARRIERA CORALLINA SI VEDE DALLO SPAZIO", categoria: "Curiosità dal Mondo" },
    { frase: "I GEYSER DI YELLOWSTONE LANCIANO ACQUA BOLLENTE", categoria: "Curiosità dal Mondo" },
    { frase: "IL MAR MORTO E COSI SALATO CHE SI GALLEGGIA", categoria: "Curiosità dal Mondo" },
    { frase: "LE TERMITI COSTRUISCONO CASE ALTE SEI METRI", categoria: "Curiosità dal Mondo" },
    { frase: "IL FORMICHIERE MANGIA TRENTA MILA INSETTI AL GIORNO", categoria: "Curiosità dal Mondo" },
    { frase: "LA SEQUOIA GIGANTE E L ALBERO PIU ALTO DEL MONDO", categoria: "Curiosità dal Mondo" },
    { frase: "IL FIORDO NORVEGESE TAGLIA LA COSTA PER CHILOMETRI", categoria: "Curiosità dal Mondo" },

    { frase: "LA RIBOLLITA TOSCANA CON PAN RAFFERMO", categoria: "In Cucina" },
    { frase: "LA BAGNA CAUDA PIEMONTESE CON VERDURE", categoria: "In Cucina" },
    { frase: "IL FRITTO MISTO ALLA PIEMONTESE", categoria: "In Cucina" },

    // ── STORIA ────────────────────────────────────────────────────────
    { frase: "LA BASTIGLIA PRESA DAL POPOLO DI PARIGI", categoria: "Storia" },
    { frase: "CESARE AUGUSTO PRIMO IMPERATORE ROMANO", categoria: "Storia" },
    { frase: "ANNIBALE ATRAVERSO LE ALPI CON GLI ELEFANTI", categoria: "Storia" },
    { frase: "LA BATTAGLIA DI WATERLOO FINE DI NAPOLEONE", categoria: "Storia" },
    { frase: "GARIBALDI SBARCA CON I MILLE IN SICILIA", categoria: "Storia" },
    { frase: "MUSSOLINI FONDA IL FASCISMO IN ITALIA", categoria: "Storia" },
    { frase: "LA SECONDA GUERRA MONDIALE PORTA DISTRUZIONE", categoria: "Storia" },
    { frase: "IL RINASCIMENTO NASCE NEL CUORE D ITALIA", categoria: "Storia" },
    { frase: "GIULIO CESARE CONQUISTÒ LA GALLIA IN ANNI", categoria: "Storia" },
    { frase: "CLEOPATRA ULTIMA REGINA DELL EGITTO ANTICO", categoria: "Storia" },
    { frase: "ROMOLO E REMO FONDATORI DELLA CITTA DI ROMA", categoria: "Storia" },
    { frase: "LA PACE DI VESTFALIA CHIUDE LA GUERRA EUROPEA", categoria: "Storia" },
    { frase: "CARLO MAGNO INCORONATO IMPERATORE A NATALE", categoria: "Storia" },
    { frase: "I ROMANI COSTRUIRONO STRADE IN TUTTO L IMPERO", categoria: "Storia" },
    { frase: "IL PAPA FIRMÒ IL TRATTATO DI LATERANO", categoria: "Storia" },
    { frase: "MARCO AURELIO IMPERATORE E FILOSOFO STOICO", categoria: "Storia" },
    { frase: "L IMPERO ROMANO D ORIENTE DURO MILLE ANNI", categoria: "Storia" },
    { frase: "VERCINGETORIGE DIFESE LA GALLIA DA CESARE", categoria: "Storia" },
    { frase: "LA RIVOLUZIONE FRANCESE ABBATTÉ IL TRONO", categoria: "Storia" },

    // ── PROVERBI E MODI DI DIRE ────────────────────────────────────────────────────────
    { frase: "CHI DORME NON PIGLIA PESCI DICE IL SAGGIO", categoria: "Proverbi e Modi di Dire" },
    { frase: "RIDE BENE CHI RIDE ULTIMO E MEGLIO", categoria: "Proverbi e Modi di Dire" },
    { frase: "OGNI LASCIATA E PERSA MAI DIMENTICARE", categoria: "Proverbi e Modi di Dire" },
    { frase: "LA SPERANZA E L ULTIMA A MORIRE SEMPRE", categoria: "Proverbi e Modi di Dire" },
    { frase: "SBAGLIANDO S IMPARA E SI CRESCE PIU FORTI", categoria: "Proverbi e Modi di Dire" },
    { frase: "IL MATTINO HA L ORO IN BOCCA OGNI GIORNO", categoria: "Proverbi e Modi di Dire" },
    { frase: "NON RIMANDARE A DOMANI QUELLO CHE PUOI FARE", categoria: "Proverbi e Modi di Dire" },
    { frase: "MEGLIO SOLI CHE MALE ACCOMPAGNATI SEMPRE", categoria: "Proverbi e Modi di Dire" },
    { frase: "CARTA CANTA E VILLAN DORME IL CONTRATTO", categoria: "Proverbi e Modi di Dire" },
    { frase: "IL DIAVOLO FA LE PENTOLE MA NON I COPERCHI", categoria: "Proverbi e Modi di Dire" },

    // ── LIBRI ────────────────────────────────────────────────────────
    { frase: "I PROMESSI SPOSI DI ALESSANDRO MANZONI", categoria: "Libri" },
    { frase: "IL CONTE DI MONTECRISTO DI DUMAS PADRE", categoria: "Libri" },
    { frase: "MOBY DICK DI HERMAN MELVILLE IL CAPODOGLIO", categoria: "Libri" },
    { frase: "DON CHISCIOTTE DELLA MANCIA DI CERVANTES", categoria: "Libri" },
    { frase: "LE TRE MOSCHETTIERI DI ALEXANDRE DUMAS", categoria: "Libri" },
    { frase: "GUERRA E PACE DI LIONE TOLSTOI ROMANZO", categoria: "Libri" },
    { frase: "IL NOME DELLA ROSA DI UMBERTO ECO", categoria: "Libri" },
    { frase: "CENT ANNI DI SOLITUDINE DI MARQUEZ", categoria: "Libri" },
    { frase: "LA FATTORIA DEGLI ANIMALI DI ORWELL", categoria: "Libri" },
    { frase: "IL PROCESSO DI FRANZ KAFKA TORMENTO", categoria: "Libri" },
    { frase: "VIAGGIO AL CENTRO DELLA TERRA DI VERNE", categoria: "Libri" },
    { frase: "LA METAMORFOSI DI FRANZ KAFKA RACCONTO", categoria: "Libri" },
    { frase: "ORGOGLIO E PREGIUDIZIO DI JANE AUSTEN", categoria: "Libri" },
    { frase: "LE MILLE E UNA NOTTE FIABE D ORIENTE", categoria: "Libri" },
    { frase: "PINOCCHIO DI COLLODI BURATTINO DI LEGNO", categoria: "Libri" },

    // ── CINEMA E ATTORI ────────────────────────────────────────────────────────
    { frase: "IL SILENZIO DEGLI INNOCENTI FILM HORROR", categoria: "Cinema e Attori" },
    { frase: "FORREST GUMP LA VITA E UNA SCATOLA DI CIOCCOLATA", categoria: "Cinema e Attori" },
    { frase: "BLADE RUNNER IL FUTURO NEI REPLICANTI", categoria: "Cinema e Attori" },
    { frase: "MATRIX LA PILLOLA ROSSA O LA BLU", categoria: "Cinema e Attori" },
    { frase: "SCHINDLER SALVA PIU DI MILLE EBREI", categoria: "Cinema e Attori" },
    { frase: "SERGIO LEONE GRANDE REGISTA DI WESTERN", categoria: "Cinema e Attori" },
    { frase: "SOPHIA LOREN VINCE L OSCAR DI IERI", categoria: "Cinema e Attori" },
    { frase: "NINO MANFREDI L ATTORE DEL NEOREALISMO", categoria: "Cinema e Attori" },
    { frase: "UNA GIORNATA PARTICOLARE DI ETTORE SCOLA", categoria: "Cinema e Attori" },
    { frase: "IL GATTOPARDO VINCE LA PALMA A CANNES", categoria: "Cinema e Attori" },
    { frase: "CHARLIE CHAPLIN RE DELLA COMMEDIA MUTA", categoria: "Cinema e Attori" },
    { frase: "BUSTER KEATON MAESTRO DEL CINEMA MUTO", categoria: "Cinema e Attori" },
    { frase: "STANLEY KUBRICK VISIONARIO DEL GRANDE SCHERMO", categoria: "Cinema e Attori" },

    // ── MUSICA ────────────────────────────────────────────────────────
    { frase: "LA NONA SINFONIA DI BEETHOVEN SENZA UDITO", categoria: "Musica" },
    { frase: "MICHAEL JACKSON IL RE DEL POP MONDIALE", categoria: "Musica" },
    { frase: "ELTON JOHN LA LEGGENDA DEL ROCK INGLESE", categoria: "Musica" },
    { frase: "BRUCE SPRINGSTEEN IL BOSS DEL NEW JERSEY", categoria: "Musica" },
    { frase: "MADONNA LA REGINA DEL POP AMERICANO", categoria: "Musica" },
    { frase: "ED SHEERAN CHITARRA E VOCE SUL PALCO", categoria: "Musica" },
    { frase: "LA TRAVIATA DI VERDI VA IN SCENA A VENEZIA", categoria: "Musica" },
    { frase: "IL RIGOLETTO DI GIUSEPPE VERDI LIRICA", categoria: "Musica" },
    { frase: "L AIDA DI VERDI AMBIENTATA IN EGITTO", categoria: "Musica" },
    { frase: "PUCCINI COMPOSE LA BOHEME E TOSCA", categoria: "Musica" },
    { frase: "CLAUDIO BAGLIONI CANTA LA VITA ITALIANA", categoria: "Musica" },
    { frase: "ZUCCHERO SUGAR FORNACIARI BLUES ITALIANO", categoria: "Musica" },
    { frase: "SANREMO IL FESTIVAL DELLA CANZONE ITALIANA", categoria: "Musica" },
    { frase: "I ROLLING STONES IL ROCK SENZA ETA", categoria: "Musica" },
    { frase: "DAVID BOWIE ZIGGY STARDUST SUL PALCO", categoria: "Musica" },

    // ── ASTRONOMIA ────────────────────────────────────────────────────────
    { frase: "URANO RUOTA SU UN FIANCO NELL ORBITA", categoria: "Astronomia" },
    { frase: "VENERE IL PIANETA PIU CALDO DEL SISTEMA", categoria: "Astronomia" },
    { frase: "LA GALASSIA DI ANDROMEDA VERRA VERSO NOI", categoria: "Astronomia" },
    { frase: "L ECLISSI SOLARE OSCURA IL SOLE A META", categoria: "Astronomia" },
    { frase: "IL TELESCOPIO JAMES WEBB GUARDA IL PASSATO", categoria: "Astronomia" },
    { frase: "LA SONDA VOYAGER VOLA FUORI DAL SISTEMA", categoria: "Astronomia" },
    { frase: "SATURNO HA SESSANTADUE LUNE CONOSCIUTE", categoria: "Astronomia" },
    { frase: "IL SOLE COMPIE UN GIRO IN VENTISEI GIORNI", categoria: "Astronomia" },
    { frase: "LE ONDE GRAVITAZIONALI SCOPERTE DA LIGO", categoria: "Astronomia" },
    { frase: "LA PRIMA FOTO DI UN BUCO NERO NELLO SPAZIO", categoria: "Astronomia" },

    // ── INVENZIONI ────────────────────────────────────────────────────────
    { frase: "JAMES WATT PERFEZIONO LA MACCHINA A VAPORE", categoria: "Invenzioni" },
    { frase: "LUIGI GALVANI SCOPRI L ELETTRICITA NEI MUSCOLI", categoria: "Invenzioni" },
    { frase: "ALESSANDRO VOLTA INVENTO LA PILA ELETTRICA", categoria: "Invenzioni" },
    { frase: "PASTEUR INVENTO IL VACCINO CONTRO LA RABBIA", categoria: "Invenzioni" },
    { frase: "ROENTGEN SCOPRI I RAGGI X NEL LABORATORIO", categoria: "Invenzioni" },
    { frase: "FERMI COSTRUI IL PRIMO REATTORE NUCLEARE", categoria: "Invenzioni" },
    { frase: "LA GOMMA VULCANIZZATA DI CHARLES GOODYEAR", categoria: "Invenzioni" },
    { frase: "ALFRED NOBEL INVENTO LA DINAMITE ESPLOSIVA", categoria: "Invenzioni" },
    { frase: "THOMAS EDISON BREVETTO OLTRE MILLE INVENZIONI", categoria: "Invenzioni" },
    { frase: "STEPHEN HAWKING STUDIA I BUCHI NERI COSMICI", categoria: "Invenzioni" },

    // ── GEOGRAFIA E VIAGGI ────────────────────────────────────────────────────────
    { frase: "IL GRAND CANYON SCAVATO DAL FIUME COLORADO", categoria: "Geografia e Viaggi" },
    { frase: "IL LAGO TITICACA TRA BOLIVIA E PERU", categoria: "Geografia e Viaggi" },
    { frase: "LA PENISOLA DI YUCATAN NEL MESSICO", categoria: "Geografia e Viaggi" },
    { frase: "IL PORTO DI SYDNEY CON L OPERA HOUSE", categoria: "Geografia e Viaggi" },
    { frase: "ANGKOR WAT IL TEMPIO PIU GRANDE DEL MONDO", categoria: "Geografia e Viaggi" },
    { frase: "LA CAPPADOCIA TURCA CON LE CIMINIERE DI FATA", categoria: "Geografia e Viaggi" },
    { frase: "IL FIORDO DI NAEROYFJORD IN NORVEGIA", categoria: "Geografia e Viaggi" },
    { frase: "LA CASCATA DI IGUAZU TRA BRASILE E ARGENTINA", categoria: "Geografia e Viaggi" },
    { frase: "LO STRETTO DI GIBILTERRA TRA AFRICA E EUROPA", categoria: "Geografia e Viaggi" },
    { frase: "LA PIANURA PADANA IL CUORE AGRICOLO D ITALIA", categoria: "Geografia e Viaggi" },
    { frase: "IL CANALE DI SUEZ COLLEGA DUE MARI DIVERSI", categoria: "Geografia e Viaggi" },
    { frase: "PETRA LA CITTA ROSA NELLA ROCCIA GIORDANA", categoria: "Geografia e Viaggi" },
    { frase: "LA TORRE EIFFEL SIMBOLO DI PARIGI NEL MONDO", categoria: "Geografia e Viaggi" },
    { frase: "IL COLOSSEO ROMANO OSPITAVA SETTANTAMILA", categoria: "Geografia e Viaggi" },
    { frase: "LA SAGRADA FAMILIA NON E ANCORA FINITA", categoria: "Geografia e Viaggi" },

    // ── IN CUCINA ────────────────────────────────────────────────────────
    { frase: "LA PASTA ALLA NORMA CON LE MELANZANE", categoria: "In Cucina" },
    { frase: "IL BRODETTO DI PESCE SULLA RIVIERA ROMAGNOLA", categoria: "In Cucina" },
    { frase: "LA PAPPA AL POMODORO TOSCANA CON IL PANE", categoria: "In Cucina" },
    { frase: "LA ZUPPA INGLESE DOLCE CON L ALCHERMES", categoria: "In Cucina" },
    { frase: "IL SALTIMBOCCA ALLA ROMANA CON PROSCIUTTO", categoria: "In Cucina" },
    { frase: "LA BISTECCA ALLA FIORENTINA COL SANGUE", categoria: "In Cucina" },
    { frase: "IL BRASATO AL BAROLO CON PURÈ DI PATATE", categoria: "In Cucina" },
    { frase: "LE TRENETTE AL PESTO GENOVESE DI BASILICO", categoria: "In Cucina" },
    { frase: "IL PANETTONE MILANESE LA NOTTE DI NATALE", categoria: "In Cucina" },
    { frase: "LA SFOGLIATELLA NAPOLETANA FRAGRANTE", categoria: "In Cucina" },
    { frase: "IL PROSCIUTTO DI PARMA STAGIONATO DODICI MESI", categoria: "In Cucina" },
    { frase: "LE TAGLIATELLE AL RAGU BOLOGNESE VERE", categoria: "In Cucina" },
    { frase: "IL GORGONZOLA ERBORINATO DELLA PIANURA", categoria: "In Cucina" },
    { frase: "IL PECORINO ROMANO GRATTATO SULLA PASTA", categoria: "In Cucina" },
    { frase: "LA POLENTA CON I FUNGHI PORCINI FRESCHI", categoria: "In Cucina" },

    // ── ANIMALI ────────────────────────────────────────────────────────
    { frase: "IL LEONE MARINO SI ABBRONZA SUGLI SCOGLI", categoria: "Animali" },
    { frase: "IL POLPO INTELLIGENTE APRE I BARATTOLI", categoria: "Animali" },
    { frase: "IL FENICOTTERO STA SU UNA GAMBA SOLA", categoria: "Animali" },
    { frase: "LA BALENA MEGATTERA SALTA FUORI DAL MARE", categoria: "Animali" },
    { frase: "L AQUILA REALE VOLA ALTISSIMA SULLE ALPI", categoria: "Animali" },
    { frase: "IL LUPO ULULATO ALLA LUNA NELLA NOTTE", categoria: "Animali" },
    { frase: "LA VOLPE ROSSA CACCIA I TOPI DI CAMPO", categoria: "Animali" },
    { frase: "IL CERVO COMBATTE CON I PALCHI IN AUTUNNO", categoria: "Animali" },
    { frase: "IL CAPRIOLO SALTA TRA GLI ALBERI DEL BOSCO", categoria: "Animali" },
    { frase: "L ORSO BRUNO DORME IN LETARGO D INVERNO", categoria: "Animali" },
    { frase: "LA LONTRA NUOTA NEI FIUMI DI MONTAGNA", categoria: "Animali" },
    { frase: "IL RICCIO SI ARROTOLA E SI DIFENDE DALLE SERPI", categoria: "Animali" },
    { frase: "IL FALCO PELLEGRINO PIOMBA A TRECENTO ALL ORA", categoria: "Animali" },

    // ── NELLO SPORT ────────────────────────────────────────────────────────
    { frase: "LA NAZIONALE ITALIANA VINCE GLI EUROPEI", categoria: "Nello Sport" },
    { frase: "L ITALIA CAMPIONE DEL MONDO A BERLINO", categoria: "Nello Sport" },
    { frase: "MARCO PANTANI SALE IN CIMA AL TOUR DE FRANCE", categoria: "Nello Sport" },
    { frase: "FEDERICA PELLEGRINI ROMPE IL RECORD MONDIALE", categoria: "Nello Sport" },
    { frase: "TAZIO NUVOLARI IL MANTOVANO VOLANTE LEGGENDA", categoria: "Nello Sport" },
    { frase: "LA MARATHON DES SABLES NEL DESERTO", categoria: "Nello Sport" },
    { frase: "LE OLIMPIADI DI BARCELLONA SONO DEL 1992", categoria: "Nello Sport" },
    { frase: "FILIPPO TORTU SPRINTER ITALIANO VELOCE", categoria: "Nello Sport" },
    { frase: "MARCELL JACOBS CAMPIONE OLIMPICO A TOKYO", categoria: "Nello Sport" },
    { frase: "FIONA MAY MEDAGLIA D ARGENTO NEL SALTO", categoria: "Nello Sport" },
    { frase: "ALEX ZANARDI CAMPIONE PARALIMPICO ASSOLUTO", categoria: "Nello Sport" },
    { frase: "JURY CHECHI IL SIGNORE DEGLI ANELLI GINNASTICA", categoria: "Nello Sport" },
    { frase: "LA MILAN CAMPIONE D EUROPA PIU VOLTE", categoria: "Nello Sport" },
    { frase: "LA JUVENTUS VINCE NOVE SCUDETTI DI FILA", categoria: "Nello Sport" },

    // ── NEL TEMPO LIBERO ────────────────────────────────────────────────────────
    { frase: "UNA SETTIMANA AL MARE CON LA FAMIGLIA", categoria: "Nel Tempo Libero" },
    { frase: "IL CAMPEGGIO NEI BOSCHI CON LA TENDA", categoria: "Nel Tempo Libero" },
    { frase: "PASSARE UN POMERIGGIO A LEGGERE UN ROMANZO", categoria: "Nel Tempo Libero" },
    { frase: "FARE UNA CROCIERA NEL MEDITERRANEO", categoria: "Nel Tempo Libero" },
    { frase: "IMPARARE A SUONARE LA CHITARRA DA SOLI", categoria: "Nel Tempo Libero" },
    { frase: "GIOCARE A CARTE CON GLI AMICI DI SEMPRE", categoria: "Nel Tempo Libero" },
    { frase: "FARE UN CORSO DI BALLO DI COPPIA", categoria: "Nel Tempo Libero" },
    { frase: "ANDARE AL MERCATO DELL ANTIQUARIATO", categoria: "Nel Tempo Libero" },
    { frase: "VISITARE UNA CANTINA VINICOLA IN TOSCANA", categoria: "Nel Tempo Libero" },
    { frase: "FARE IL TOUR DEI BORGHI PIU BELLI D ITALIA", categoria: "Nel Tempo Libero" },

    // ── USI E COSTUMI ────────────────────────────────────────────────────────
    { frase: "LA NOTTE DI CAPODANNO IN PIAZZA CON I FUOCHI", categoria: "Usi e Costumi" },
    { frase: "LA VENDEMMIA A SETTEMBRE NEI VIGNETI", categoria: "Usi e Costumi" },
    { frase: "LA TOMBOLA DI NATALE CON LA FAMIGLIA", categoria: "Usi e Costumi" },
    { frase: "LA PASSEGGIATA SERALE IN CENTRO STORICO", categoria: "Usi e Costumi" },
    { frase: "IL CENONE DELLA VIGILIA CON IL PESCE", categoria: "Usi e Costumi" },
    { frase: "LA GARA DEL PALIO CON I CAVALLI IN PISTA", categoria: "Usi e Costumi" },
    { frase: "IL VEGLIONE DI CARNEVALE CON LA MASCHERA", categoria: "Usi e Costumi" },
    { frase: "L EPIFANIA PORTA I DONI AI BAMBINI BUONI", categoria: "Usi e Costumi" },
    { frase: "IL RITO DEL CAFFE AL BAR LA MATTINA", categoria: "Usi e Costumi" },
    { frase: "LA PARTITA A CARTE NELLA PIAZZA DEL PAESE", categoria: "Usi e Costumi" },

    // ── NATURA E AMBIENTE ────────────────────────────────────────────────────────
    { frase: "IL PARCO NAZIONALE DEL SERENGETI IN AFRICA", categoria: "Natura e Ambiente" },
    { frase: "LA BARRIERA CORALLINA SI SBIANCA PER IL CALDO", categoria: "Natura e Ambiente" },
    { frase: "IL GHIACCIAIO DEL VATNAJOKULL IN ISLANDA", categoria: "Natura e Ambiente" },
    { frase: "LA FORESTA DI BAMBÙ IN GIAPPONE CRESCE VELOCE", categoria: "Natura e Ambiente" },
    { frase: "I PANDA ROSSI VIVONO NEI BOSCHI D ALTITUDINE", categoria: "Natura e Ambiente" },
    { frase: "IL PARCO DEL GRAN PARADISO RISERVA ALPINA", categoria: "Natura e Ambiente" },
    { frase: "I DELFINI COMUNICANO CON IL LORO LINGUAGGIO", categoria: "Natura e Ambiente" },
    { frase: "LA TUNDRA ARTICA OSPITA GLI ORSI POLARI", categoria: "Natura e Ambiente" },
    { frase: "LE SAVANE AFRICANE SI ESTENDONO PER MIGLIA", categoria: "Natura e Ambiente" },
    { frase: "IL LAGO DI COMO RIFLETTE LE MONTAGNE ALPINE", categoria: "Natura e Ambiente" },

    // ── SPETTACOLO ────────────────────────────────────────────────────────
    { frase: "FIORELLO ILLUMINA IL PALCO DELL ARISTON", categoria: "Spettacolo" },
    { frase: "BENIGNI LEGGE DANTE IN PIAZZA COL PUBBLICO", categoria: "Spettacolo" },
    { frase: "GABRIELE MUCCINO REGISTA DI SUCCESSO USA", categoria: "Spettacolo" },
    { frase: "CHRISTIAN DE SICA FIGLIO D ARTE E COMICO", categoria: "Spettacolo" },
    { frase: "GIGI PROIETTI SIGNORE DEL TEATRO ROMANO", categoria: "Spettacolo" },
    { frase: "NINO FRASSICA PERSONAGGIO CULT DELLA TV", categoria: "Spettacolo" },
    { frase: "IL TEATRO LA FENICE DI VENEZIA BRUCIÒ DUE VOLTE", categoria: "Spettacolo" },
    { frase: "L OPERA DI VIENNA LA PIU PRESTIGIOSA", categoria: "Spettacolo" },

    // ── ARTE E PITTURA ────────────────────────────────────────────────────────
    { frase: "IL CENACOLO DI LEONARDO DIPINTO A MILANO", categoria: "Arte e Pittura" },
    { frase: "LA CAPPELLA SISTINA CAPOLAVORO DI MICHELANGELO", categoria: "Arte e Pittura" },
    { frase: "L URLO DI MUNCH ESPRIME ANSIA E TERRORE", categoria: "Arte e Pittura" },
    { frase: "LA RAGAZZA CON L ORECCHINO DI PERLA DI VERMEER", categoria: "Arte e Pittura" },
    { frase: "IL PENSATORE DI RODIN SCULTURA IN BRONZO", categoria: "Arte e Pittura" },
    { frase: "I GIRASOLI DI VAN GOGH SPLENDONO DI GIALLO", categoria: "Arte e Pittura" },
    { frase: "LA PRIMAVERA DI BOTTICELLI AGLI UFFIZI", categoria: "Arte e Pittura" },
    { frase: "L ADORAZIONE DEI MAGI DI LEONARDO", categoria: "Arte e Pittura" },
    { frase: "RAFFAELLO SANZIO LA SCUOLA DI ATENE", categoria: "Arte e Pittura" },
    { frase: "MICHELANGELO SCOLPISCE LA PIETA DI MARMO", categoria: "Arte e Pittura" },
    { frase: "IL COLORE AZZURRO DI KLEIN BREVETTATO", categoria: "Arte e Pittura" },
    { frase: "LA ZATTERA DELLA MEDUSA DI GERICAULT", categoria: "Arte e Pittura" },

    // ── TECNOLOGIA ────────────────────────────────────────────────────────
    { frase: "L INTELLIGENZA ARTIFICIALE GENERATIVA", categoria: "Tecnologia" },
    { frase: "IL MODELLO LINGUISTICO IMPARA DAI TESTI", categoria: "Tecnologia" },
    { frase: "LA FUSIONE NUCLEARE FONTE DI ENERGIA PULITA", categoria: "Tecnologia" },
    { frase: "IL RAZZO RIUTILIZZABILE DI SPACEX ATTERRA", categoria: "Tecnologia" },
    { frase: "LA GUIDA AUTONOMA SENZA PILOTA UMANO", categoria: "Tecnologia" },
    { frase: "IL CHIP NEURALE CONNETTE IL CERVELLO AL PC", categoria: "Tecnologia" },
    { frase: "LA STAMPA 3D CREA ORGANI ARTIFICIALI", categoria: "Tecnologia" },
    { frase: "IL SATELLITE STARLINK PORTA INTERNET OVUNQUE", categoria: "Tecnologia" },

    // ── CURIOSITÀ DAL MONDO ────────────────────────────────────────────────────────
    { frase: "LE MEDUSE SONO COMPOSTE PER IL NOVANTA DI ACQUA", categoria: "Curiosità dal Mondo" },
    { frase: "LA FORMICA PUO TRASPORTARE CENTO VOLTE IL SUO PESO", categoria: "Curiosità dal Mondo" },
    { frase: "IL CERVELLO UMANO CONSUMA VENTI PERCENTO DELL ENERGIA", categoria: "Curiosità dal Mondo" },
    { frase: "GLI ELEFANTI SONO GLI UNICI CHE SEPPELLISCONO I MORTI", categoria: "Curiosità dal Mondo" },
    { frase: "LA LUNA SI ALLONTANA DALLA TERRA DI QUATTRO CM L ANNO", categoria: "Curiosità dal Mondo" },
    { frase: "IL CUORE DI UNA BALENA PESA SETTECENTO CHILI", categoria: "Curiosità dal Mondo" },
    { frase: "IL CALAMAR GIGANTE HA GLI OCCHI PIU GRANDI DEL MONDO", categoria: "Curiosità dal Mondo" },
    { frase: "LA LUMACA PUO DORMIRE PER TRE ANNI DI FILA", categoria: "Curiosità dal Mondo" },
    { frase: "UN LAMPO E PIU CALDO DELLA SUPERFICIE DEL SOLE", categoria: "Curiosità dal Mondo" },
    { frase: "LA LINGUA DELLA GIRAFFA E NERA E LUNGA", categoria: "Curiosità dal Mondo" },

    // ── ANATOMIA ────────────────────────────────────────────────────────
    { frase: "IL CUORE ADULTO POMPA CINQUE LITRI AL MINUTO", categoria: "Anatomia" },
    { frase: "LE OSSA SONO PIU DURE DELL ACCIAIO A PESO", categoria: "Anatomia" },
    { frase: "IL CORPO UMANO HA TRECENTOSESSANTA OSSA DA BAMBINO", categoria: "Anatomia" },
    { frase: "I POLMONI ESPANSI COPRONO DUE CAMPI DA TENNIS", categoria: "Anatomia" },
    { frase: "LA RETINA DELL OCCHIO HA CENTOVENTI MILIONI DI CELLULE", categoria: "Anatomia" },
    { frase: "IL FEGATO E IL SOLO ORGANO CHE SI RIGENERA", categoria: "Anatomia" },
    { frase: "LA PELLE SI RINNOVA COMPLETAMENTE IN UN MESE", categoria: "Anatomia" },
    { frase: "IL SANGUE COMPIE IL GIRO DEL CORPO IN UN MINUTO", categoria: "Anatomia" },

    // ── SINONIMI E CONTRARI ────────────────────────────────────────────────────────
    { frase: "ALLEGRO E SINONIMO DI VIVACE E GIOIOSO", categoria: "Sinonimi e Contrari" },
    { frase: "LENTO E L OPPOSTO DI VELOCE E RAPIDO", categoria: "Sinonimi e Contrari" },
    { frase: "BUONO SI CONTRAPPONE A CATTIVO E MALVAGIO", categoria: "Sinonimi e Contrari" },
    { frase: "CHIARO E OSCURO SONO DUE OPPOSTI NETTI", categoria: "Sinonimi e Contrari" },
    { frase: "VECCHIO E GIOVANE INDICANO ETA DIVERSE", categoria: "Sinonimi e Contrari" },
    { frase: "APERTO E CHIUSO SONO STATI CONTRARI FISICI", categoria: "Sinonimi e Contrari" },
    { frase: "INIZIARE E FINIRE SONO VERBI CONTRARI", categoria: "Sinonimi e Contrari" },
    { frase: "CORTO E LUNGO MISURANO LUNGHEZZE DIVERSE", categoria: "Sinonimi e Contrari" },
];
