const croceDomande = [
    { def: "Capoluogo della Liguria, porto importante", sol: "GENOVA" },
    { def: "La città dei canali e delle gondole", sol: "VENEZIA" },
    { def: "Fiume che attraversa Roma", sol: "TEVERE" },
    { def: "Il satellite naturale della Terra", sol: "LUNA" },
    { def: "Il pianeta più grande del sistema solare", sol: "GIOVE" },
    { def: "Capitale della Francia", sol: "PARIGI" },
    { def: "Il metallo prezioso giallo per eccellenza", sol: "ORO" },
    { def: "Strumento a corde pizzicate di forma triangolare", sol: "ARPA" },
    { def: "Regione italiana con capoluogo Palermo", sol: "SICILIA" },
    { def: "Uccello simbolo della pace", sol: "COLOMBA" },
    { def: "Lago più grande d'Italia", sol: "GARDA" },
    { def: "Il pianeta rosso", sol: "MARTE" },
    { def: "La montagna più alta del mondo", sol: "EVEREST" },
    { def: "Lo scrittore della Divina Commedia", sol: "DANTE" },
    { def: "Il compositore della Quinta Sinfonia", sol: "BEETHOVEN" },
    { def: "Grande isola con capoluogo Cagliari", sol: "SARDEGNA" },
    { def: "Il frutto della vite", sol: "UVA" },
    { def: "Strumento a fiato dai suoni squillanti", sol: "TROMBA" },
    { def: "La capitale della Spagna", sol: "MADRID" },
    { def: "Il re dei felini", sol: "LEONE" },
    { def: "Antico anfiteatro di Roma", sol: "COLOSSEO" },
    { def: "La moneta unica europea", sol: "EURO" },
    { def: "Leggendario cavallo alato della mitologia greca", sol: "PEGASO" },
    { def: "Pittore della Gioconda", sol: "LEONARDO" },
    { def: "Scienziato della teoria della relatività", sol: "EINSTEIN" },
    { def: "Il numero che viene dopo il nove", sol: "DIECI" },
    { def: "Animale con la proboscide", sol: "ELEFANTE" },
    { def: "Lo sport nazionale degli americani con la mazza", sol: "BASEBALL" },
    { def: "Rettile lento dal guscio duro", sol: "TARTARUGA" },
    { def: "La capitale del Giappone", sol: "TOKYO" },
    { def: "Strumento a tastiera di Chopin", sol: "PIANOFORTE" },
    { def: "Il colore del cielo sereno", sol: "AZZURRO" },
    { def: "Fiume più lungo d'Italia", sol: "PO" },
    { def: "Il vulcano attivo della Sicilia", sol: "ETNA" },
    { def: "Cetaceo più grande del mondo", sol: "BALENA" },
    { def: "La capitale della Germania", sol: "BERLINO" },
    { def: "Personaggio di Shakespeare, principe di Danimarca", sol: "AMLETO" },
    { def: "Il pianeta con gli anelli", sol: "SATURNO" },
    { def: "Felino delle nevi con il manto maculato", sol: "LEOPARDO" },
    { def: "Il metallo conduttore dei fili elettrici", sol: "RAME" },
    { def: "Inventore del telefono", sol: "BELL" },
    { def: "La regione italiana con la gondola nel simbolo", sol: "VENETO" },
    { def: "La stagione dei fiori", sol: "PRIMAVERA" },
    { def: "Il più famoso quadro di Van Gogh con stelle", sol: "NOTTE" },
    { def: "Gioco di carte italiano con le briscole", sol: "BRISCOLA" },
    { def: "Il continente più grande del mondo", sol: "ASIA" },
    { def: "Il pianeta più vicino al Sole", sol: "MERCURIO" },
    { def: "La capitale d'Australia", sol: "CANBERRA" },
    { def: "Scrittore di Don Chisciotte", sol: "CERVANTES" },
    { def: "Animale che cambia colore per mimetizzarsi", sol: "CAMALEONTE" },
    { def: "La montagna sacra del Giappone", sol: "FUJI" },
    { def: "Strumento di navigazione che indica il nord", sol: "BUSSOLA" },
    { def: "Il matematico della mela che cadde", sol: "NEWTON" },
    { def: "Il deserto più grande del mondo", sol: "SAHARA" },
    { def: "La capitale del Brasile", sol: "BRASILIA" },
    { def: "Personaggio Disney figlio di Mufasa", sol: "SIMBA" },
    { def: "Lo sport invernale con le racchette", sol: "SCI" },
    { def: "Pittore olandese delle Girasoli", sol: "VANGOGH" },
    { def: "Il gas che respiriamo per vivere", sol: "OSSIGENO" },
    { def: "Il gioco degli scacchi ha questa figura con la corona", sol: "REGINA" },
    { def: "Scrittore di Pinocchio", sol: "COLLODI" },
    { def: "Il colore ottenuto mescolando rosso e blu", sol: "VIOLA" },
    { def: "L'isola di Robinson Crusoe nell'immaginario", sol: "ISOLA" },
    { def: "La regione con il capoluogo Firenze", sol: "TOSCANA" },
    { def: "Il mare a est dell'Italia", sol: "ADRIATICO" },
    { def: "Animale che dorme tutto l'inverno", sol: "ORSO" },
    { def: "Il simbolo chimico dell'acqua ha due di questo gas", sol: "IDROGENO" },
    { def: "La capitale dell'Argentina", sol: "BUENOSAIRES" },
    { def: "Il navigatore che scoprì l'America nel 1492", sol: "COLOMBO" },
    { def: "Sport olimpico praticato in piscina", sol: "NUOTO" },
    { def: "La montagna che divide Italia e Francia nelle Alpi", sol: "BIANCO" },
    { def: "L'inventore della stampa a caratteri mobili", sol: "GUTENBERG" },
    { def: "Il palazzo del governo italiano a Roma", sol: "QUIRINALE" },
    { def: "Lo strumento usato dall'astronomo per osservare le stelle", sol: "TELESCOPIO" },
    { def: "Rettile senza zampe", sol: "SERPENTE" },
    { def: "La capitale della Russia", sol: "MOSCA" },
    { def: "Il termine musicale per suono più acuto", sol: "SOPRANO" },
    { def: "Antico guerriero romano", sol: "GLADIATORE" },
    { def: "Il continente al Polo Sud", sol: "ANTARTIDE" },
    { def: "Lo sport con il pallone ovale", sol: "RUGBY" },
    { def: "Il re degli scacchi è sotto attacco: situazione di", sol: "SCACCO" },
    { def: "Lo scrittore de I Promessi Sposi", sol: "MANZONI" },
    { def: "Frutto tropicale giallo a forma di mezzaluna", sol: "BANANA" },
    { def: "La capitale del Portogallo", sol: "LISBONA" },
    { def: "Il componente principale della fotosintesi clorofilliana", sol: "CLOROFILLA" },
    { def: "Il matematico di Siracusa famoso per il principio", sol: "ARCHIMEDE" },
    { def: "La regione italiana del Vesuvio", sol: "CAMPANIA" },
    { def: "Il colore della foglia in autunno avanzato", sol: "GIALLO" },
    { def: "Sport con racchette e volano", sol: "BADMINTON" },
    { def: "Lo strumento del chirurgo per tagliare", sol: "BISTURI" },
    { def: "Il paese asiatico della Grande Muraglia", sol: "CINA" },
    { def: "La figura geometrica a tre lati", sol: "TRIANGOLO" },
    { def: "Il re degli scacchi: il pezzo più importante", sol: "RE" },
    { def: "L'artista fiorentino che scolpì il David", sol: "MICHELANGELO" },
    { def: "Il mare che bagna Napoli", sol: "TIRRENO" },
    { def: "La regione del Piemonte con il capoluogo", sol: "TORINO" },
    { def: "Strumento di misura della temperatura", sol: "TERMOMETRO" },
    { def: "Il navigatore italiano che diede il nome all'America", sol: "VESPUCCI" },
    { def: "La città con la Torre Pendente", sol: "PISA" },
    { def: "Il minerale che compone le matite", sol: "GRAFITE" },
    { def: "Grande deserto freddo dell'Asia centrale", sol: "GOBI" },
    { def: "Il legame chimico tra atomi di ossigeno nell'acqua", sol: "COVALENTE" },
    { def: "Si usa per scrivere sulla lavagna di ardesia", sol: "GESSO" },
    { def: "La capitale della Grecia antica e moderna", sol: "ATENE" },
    { def: "Mammifero marino noto per la sua intelligenza", sol: "DELFINO" },
    { def: "La regione con il capoluogo Bari", sol: "PUGLIA" },
    { def: "La stella più vicina alla Terra", sol: "SOLE" },
    { def: "Lo stretto che separa Sicilia e Calabria", sol: "MESSINA" },
    { def: "Il gas nobile usato nelle insegne luminose", sol: "NEON" },
    { def: "L'eroe greco che uccise Medusa", sol: "PERSEO" },
    { def: "La capitale della Turchia", sol: "ANKARA" },
    { def: "Il materiale di cui sono fatti i denti", sol: "SMALTO" },
    { def: "Grande fiume africano che sfocia nel Mediterraneo", sol: "NILO" },
    { def: "Lo sport di Valentino Rossi", sol: "MOTOCICLISMO" },
    { def: "La ghiandola che produce l'insulina", sol: "PANCREAS" },
    { def: "Il leggendario fondatore di Roma con Remo", sol: "ROMOLO" },
    { def: "Lo stato con la bandiera a stelle e strisce", sol: "USA" },
    { def: "L'osso più lungo del corpo umano", sol: "FEMORE" },
    { def: "Il primo uomo nello spazio", sol: "GAGARIN" },
    { def: "Città svizzera sede del CERN", sol: "GINEVRA" },
    { def: "Lo strumento musicale di Sherlock Holmes", sol: "VIOLINO" },
    { def: "La capitale della Svizzera", sol: "BERNA" },
    { def: "L'animale che porta i piccoli nel marsupio", sol: "CANGURO" },
    { def: "Il metallo usato per le lattine di bibite", sol: "ALLUMINIO" },
    { def: "Il vulcano che distrusse Pompei", sol: "VESUVIO" },
    { def: "La città della famosa Oktoberfest", sol: "MONACO" },
    { def: "Il pigmento che colora la nostra pelle", sol: "MELANINA" },
    { def: "Lo scrittore di Sherlock Holmes", sol: "DOYLE" },
    { def: "Il punto più profondo degli oceani", sol: "MARIANNE" },
    { def: "La capitale dell'Egitto", sol: "CAIRO" },
    { def: "Il costituente principale delle ossa", sol: "CALCIO" },
    { def: "L'autore de Il piccolo principe", sol: "SAINTEXUPERY" },
    { def: "Il processo con cui le piante creano nutrimento", sol: "FOTOSINTESI" },
    { def: "L'unità di misura della corrente elettrica", sol: "AMPERE" },
    { def: "La capitale della Cina", sol: "PECHINO" },
    { def: "L'insetto che produce il miele", sol: "APE" },
    { def: "Il mare tra Europa e Africa", sol: "MEDITERRANEO" },
    { def: "La parte dell'occhio che dà il colore", sol: "IRIDE" },
    { def: "Il metallo più leggero esistente", sol: "LITIO" },
    { def: "La capitale dell'India", sol: "NEWDELHI" },
    { def: "Lo scienziato che inventò la lampadina", sol: "EDISON" },
    { def: "Il pianeta più lontano dal Sole", sol: "NETTUNO" },
    { def: "La capitale dell'Inghilterra", sol: "LONDRA" },
    { def: "Il muscolo che pompa il sangue", sol: "CUORE" },
    { def: "La regione con il capoluogo Ancona", sol: "MARCHE" },
    { def: "Il periodo di 1000 anni", sol: "MILLENNIO" },
    { def: "Si usa per asciugarsi dopo la doccia", sol: "ASCIUGAMANO" },
    { def: "Mammifero che vola", sol: "PIPISTRELLO" },
    { def: "Lo scienziato che inventò la pila", sol: "VOLTA" },
    { def: "Il metallo usato per i gioielli meno caro dell'oro", sol: "ARGENTO" },
    { def: "La regione con il capoluogo L'Aquila", sol: "ABRUZZO" },
    { def: "La stella polare indica questa direzione", sol: "NORD" },
    { def: "Lo stato con la bandiera a cerchio rosso", sol: "GIAPPONE" },
    { def: "Lo strumento per misurare la pressione atmosferica", sol: "BAROMETRO" },
    { def: "L'eroe greco che tallonava Ettore a Troia", sol: "ACHILLE" },
    { def: "La capitale dell'Austria", sol: "VIENNA" },
    { def: "La sostanza di cui sono fatte le unghie", sol: "CHERATINA" },
    { def: "L'organo che filtra il sangue", sol: "RENE" },
    { def: "La leggendaria fondazione di Roma avvenne su questo colle", sol: "PALATINO" },
    { def: "Lo stato con la Torre Eiffel", sol: "FRANCIA" },
    { def: "Il primo uomo sulla Luna", sol: "ARMSTRONG" },
    { def: "La parte del fiore che attira gli insetti", sol: "PETALO" },
    { def: "Città belga sede della Commissione Europea", sol: "BRUXELLES" },
    { def: "Il deserto di sale più grande del mondo in Bolivia", sol: "UYUNI" },
    { def: "La capitale dell'Olanda (Paesi Bassi)", sol: "AMSTERDAM" },
    { def: "L'animale più veloce del mondo", sol: "GHEPARDO" },
    { def: "Il materiale trasparente per le finestre", sol: "VETRO" },
    { def: "La sostanza che trasporta l'ossigeno nel sangue", sol: "EMOGLOBINA" },
    { def: "L'autore di Oliver Twist", sol: "DICKENS" },
    { def: "La capitale della Svezia", sol: "STOCCOLMA" },
    { def: "L'unità di misura della frequenza", sol: "HERTZ" },
    { def: "La trasformazione da liquido a vapore", sol: "EVAPORAZIONE" },
    { def: "L'unità di misura della potenza elettrica", sol: "WATT" },
    { def: "La capitale della Corea del Sud", sol: "SEOUL" },
    { def: "L'insetto che lavora in gruppo nel formicaio", sol: "FORMICA" },
    { def: "La membrana dell'orecchio che vibra", sol: "TIMPANO" },
    { def: "Il metallo dei famosi 'Bronzi' di Riace", sol: "BRONZO" },
    { def: "La capitale della Thailandia", sol: "BANGKOK" },
    { def: "Il pianeta più piccolo (non più considerato tale)", sol: "PLUTONE" },
    { def: "Il protagonista di Dragon Ball", sol: "GOKU" },
    { def: "Il calciatore che ha vinto più Palloni d'Oro", sol: "MESSI" },
    { def: "Il deserto di Guerre Stellari dove vive Luke", sol: "TATOOINE" },
    { def: "Il principe dei Saiyan", sol: "VEGETA" },
    { def: "Il regista del film Titanic", sol: "CAMERON" },
    { def: "Il drago che esaudisce i desideri in Dragon Ball", sol: "SHENRON" },
    { def: "Lo stadio di Milano soprannominato La Scala del Calcio", sol: "SANSIRO" },
    { def: "L'attore che interpreta l'agente 007 James Bond", sol: "CRAIG" },
    { def: "Tecnica speciale di Goku: l'onda...", sol: "KAMEHAMEHA" },
    { def: "Il capitano storico della Roma con la maglia numero 10", sol: "TOTTI" },
    { def: "Il primo film della saga di Harry Potter: la pietra...", sol: "FILOSOFALE" },
    { def: "L'amico di Goku senza naso", sol: "CRILIN" },
    { def: "Squadra di calcio di Madrid che veste di bianco", sol: "REAL" },
    { def: "L'attore protagonista di Forrest Gump", sol: "HANKS" },
    { def: "Fusione tra Goku e Vegeta con gli orecchini", sol: "VEGETTO" },
    { def: "Il cattivo di Avengers con il guanto dell'infinito", sol: "THANOS" },
    { def: "Il Maestro di Goku che vive su un'isoletta", sol: "ROSHI" },
    { def: "Il trofeo vinto dall'Italia nel 1934, 1938, 1982 e 2006", sol: "MONDIALE" },
    { def: "Il maghetto occhialuto creato da J.K. Rowling", sol: "HARRY" },
    { def: "Il figlio di Goku che sconfigge Cell", sol: "GOHAN" },
    { def: "Squadra inglese che gioca ad Anfield e canta You'll Never Walk Alone", sol: "LIVERPOOL" },
    { def: "Il compagno di Batman a Gotham City", sol: "ROBIN" },
    { def: "Trasformazione bionda dei guerrieri Saiyan", sol: "SUPERSAIYAN" },
    { def: "Il calciatore portoghese con la sigla CR7", sol: "RONALDO" },
    { def: "Il film con gli alieni blu sul pianeta Pandora", sol: "AVATAR" },
    { def: "Il nemico rosa che trasforma le persone in cioccolato", sol: "BUU" },
    { def: "L'allenatore dell'Italia campione d'Europa 2021", sol: "MANCINI" },
    { def: "Celebre film di animazione Disney con Simba", sol: "RELEONE" },
    { def: "L'oggetto cercato dai guerrieri Z: le sfere del...", sol: "DRAGO" },
    { def: "Il portiere capitano dell'Italia nel 2006", sol: "BUFFON" },
    { def: "L'archeologo con la frusta interpretato da Harrison Ford", sol: "INDIANA" },
    { def: "Nemico alieno che ha tre trasformazioni prima della forma perfetta", sol: "FREEZER" },
    { def: "Il parco con i dinosauri creato da Steven Spielberg", sol: "JURASSIC" },
    { def: "L'arma preferita di Trunks", sol: "SPADA" },
    { def: "La squadra di calcio soprannominata La Vecchia Signora", sol: "JUVENTUS" },
    { def: "Il premio Oscar per il miglior film straniero di Sorrentino: La Grande...", sol: "BELLEZZA" },
    { def: "La cittadina dove vive Goku con la sua famiglia", sol: "PAOZU" },
    { def: "L'attaccante svedese che si paragona a un Dio", sol: "IBRAHIMOVIC" },
    { def: "Film horror con il pagliaccio Pennywise", sol: "IT" },
    { def: "Il robot creato dal Dr. Gelo che assorbe gli androidi", sol: "CELL" },
    { def: "Il giocatore di calcio che segna un gol compie una...", sol: "RETE" },
    { def: "Il film di Tarantino con John Travolta e Samuel L. Jackson", sol: "PULPFICTION" },
    { def: "Il numero di maglia tipico del centravanti", sol: "NOVE" },
    { def: "La capitale del cinema americano", sol: "HOLLYWOOD" },
    { def: "Il Dio della Distruzione che ama il cibo della Terra", sol: "BEERUS" },
    { def: "La massima competizione europea per club di calcio", sol: "CHAMPIONS" },
    { def: "Il leggendario spadaccino con la maschera e il mantello", sol: "ZORRO" },
    { def: "La particella elementare con carica negativa", sol: "ELETTRONE" },
    { def: "Lo stato americano con la città di Las Vegas", sol: "NEVADA" },
    { def: "Il celebre burattino che sognava di diventare bambino", sol: "PINOCCHIO" },
    { def: "Si dice di un'operazione che non ha avuto successo", sol: "FALLIMENTO" },
    { def: "Il metallo prezioso che non si ossida", sol: "PLATINO" },
    { def: "L'eroe che liberò il Sud America", sol: "BOLIVAR" },
    { def: "Lo è la persona che non dice mai bugie", sol: "SINCERA" },
    { def: "Il fiume che bagna Firenze e Pisa", sol: "ARNO" },
    { def: "L'albero che produce le ghiande", sol: "QUERCIA" },
    { def: "La storica capitale dell'Impero Ottomano", sol: "ISTANBUL" },
    { def: "Il veleno contenuto nelle sigarette", sol: "NICOTINA" },
    { def: "Il creatore della saga di Star Wars", sol: "LUCAS" },
    { def: "La pietra preziosa più dura in natura", sol: "DIAMANTE" },
    { def: "L'animale che simboleggia la furbizia", sol: "VOLPE" },
    { def: "Il mitico gigante con un occhio solo", sol: "CICLOPE" },
    { def: "La città sede del Parlamento Europeo", sol: "STRASBURGO" },
    { def: "Si usa per misurare gli angoli in geometria", sol: "GONIOMETRO" },
    { def: "Il leggendario arciere di Sherwood", sol: "ROBINHOOD" },
    { def: "La regione con il capoluogo Perugia", sol: "UMBRIA" },
    { def: "Il nome del cavallo di Don Chisciotte", sol: "RONZINANTE" },
    { def: "Lo strumento che indica la velocità in auto", sol: "TACHIMETRO" },
    { def: "Il metallo usato per le vecchie monete da cento lire", sol: "ACMONITAL" },
    { def: "La capitale della Danimarca", sol: "COPENAGHEN" },
    { def: "L'eroina che guidò i francesi contro gli inglesi", sol: "GIOVANNA" },
    { def: "La stella più luminosa del cielo notturno", sol: "SIRIO" },
    { def: "L'organo che permette di sentire i sapori", sol: "LINGUA" },
    { def: "Il celebre detective creato da Agatha Christie", sol: "POIROT" },
    { def: "Lo sport di Michael Jordan", sol: "BASKET" },
    { def: "La capitale della Scozia", sol: "EDIMBURGO" },
    { def: "Lo stato europeo con la bandiera blu e gialla", sol: "SVEZIA" },
    { def: "Il nome della nave di Capitan Uncino", sol: "JOLLYROGER" },
    { def: "Il componente della cellula che contiene il DNA", sol: "NUCLEO" },
    { def: "Il celebre film di Kubrick con l'intelligenza HAL 9000", sol: "ODISSEA" },
    { def: "La regione con il capoluogo Catanzaro", sol: "CALABRIA" },
    { def: "Il velivolo dei fratelli Wright", sol: "AEROPLANO" },
    { def: "L'unità di misura della resistenza elettrica", sol: "OHM" },
    { def: "La capitale del Messico", sol: "CITTADELMESSICO" },
    { def: "Il metallo contenuto negli spinaci (seppur poco)", sol: "FERRO" },
    { def: "L'autore della poesia L'Infinito", sol: "LEOPARDI" },
    { def: "La parte del computer che elabora i dati", sol: "PROCESSORE" },
    { def: "Il leggendario continente sprofondato negli abissi", sol: "ATLANTIDE" },
    { def: "La capitale del Vietnam", sol: "HANOI" },
    { def: "Il pianeta più luminoso visto dalla Terra", sol: "VENERE" },
    { def: "Lo strumento per osservare i microbi", sol: "MICROSCOPIO" },
    { def: "Il gioco in cui si vince con un terno o una cinquina", sol: "TOMBOLA" },
    { def: "Lo è la persona che ha modi garbati e gentili", sol: "CORTESE" },
    { def: "Il leggendario re che trasformava tutto in oro", sol: "MIDA" },
    { def: "Il nome del satellite lanciato dai russi nel 1957", sol: "SPUTNIK" },
    { def: "Il fiume che bagna la città di Londra", sol: "TAMIGI" },
    { def: "Si dice di un oggetto che non ha prezzo", sol: "INCALCOLABILE" },
    { def: "La protagonista del film Colazione da Tiffany", sol: "AUDREY" },
    { def: "Il celebre ammutinamento avvenuto su una nave inglese", sol: "BOUNTY" },
    { def: "Lo stato con la città di Casablanca", sol: "MAROCCO" },
    { def: "Il muscolo che ci permette di masticare", sol: "MASSETERE" },
    { def: "Il pittore che dipinse l'Urlo", sol: "MUNCH" },
    { def: "La famosa via di Roma che porta a San Pietro", sol: "CONCILIAZIONE" },
    { def: "Il gas che compone la maggior parte dell'atmosfera", sol: "AZOTO" },
    { def: "L'eroe che sconfisse il Minotauro nel labirinto", sol: "TESEO" },
    { def: "La capitale della Norvegia", sol: "OSLO" },
    { def: "Il termine che indica il verso della pecora", sol: "BELATO" },
    { def: "L'autore del romanzo Il nome della rosa", sol: "ECO" },
    { def: "Lo strumento che serve per livellare un piano", sol: "LIVELLA" },
    { def: "La storica regina d'Egitto amante di Antonio", sol: "CLEOPATRA" },
    { def: "Il monte su cui Mosè ricevette le tavole", sol: "SINAI" },
    { def: "Lo scrittore che inventò il Commissario Montalbano", sol: "CAMILLERI" },
    { def: "Il nome della famosa spia Mata...", sol: "HARI" },
    { def: "La capitale della Finlandia", sol: "HELSINKI" },
    { def: "Il metallo usato per i filamenti delle vecchie lampadine", sol: "TUNGSTENO" },
    { def: "Il cavaliere che cercava il Sacro Graal", sol: "PARSIFAL" },
    { def: "Lo stato che ha come simbolo la foglia d'acero", sol: "CANADA" },
    { def: "Il famoso navigatore portoghese che doppiò il Capo di Buona Speranza", sol: "VASCODA GAMA" },
    { def: "Il dolce tipico di Milano che si mangia a Natale", sol: "PANETTONE" },
    { def: "La regione italiana con il capoluogo Campobasso", sol: "MOLISE" },
    { def: "Lo strumento usato dal medico per ascoltare il battito", sol: "FONENDOSCOPIO" },
    { def: "La città con il celebre Santuario di Padre Pio", sol: "SAN GIOVANNI ROTONDO" },
    { def: "Il nome della madre di Gesù", sol: "MARIA" },
    { def: "Il minerale più morbido secondo la scala di Mohs", sol: "TALCO" },
    { def: "La capitale della Repubblica Ceca", sol: "PRAGA" },
    { def: "Il gioco con le tessere bianche e i puntini neri", sol: "DOMINO" },
    { def: "Il compositore delle Quattro Stagioni", sol: "VIVALDI" },
    { def: "La regione con la città di Matera", sol: "BASILICATA" },
    { def: "Il termine sportivo per una vittoria schiacciante", sol: "CAPPOTTO" },
    { def: "La sostanza usata per sterilizzare l'acqua delle piscine", sol: "CLORO" },
    { def: "Il patriarca che costruì l'arca per il diluvio", sol: "NOE" },
    { def: "La parte superiore della nave", sol: "PONTE" },
    { def: "Il deserto di sale tra i più grandi al mondo", sol: "ATACAMA" },
    { def: "Lo scienziato che scoprì la penicillina", sol: "FLEMING" },
    { def: "Il film di animazione con la pesciolina smemorata Dory", sol: "NEMO" },
    { def: "Il leggendario re della tavola rotonda", sol: "ARTU" },
    { def: "Il colore che si ottiene unendo bianco e rosso", sol: "ROSA" },
    { def: "La storica rassegna canora estiva ideata da Vittorio Salvetti", sol: "FESTIVALBAR" },
    { def: "Lo è la persona che agisce con cautela e attenzione", sol: "PRUDENTE" },
    { def: "Il nome del faraone che fece costruire la piramide più alta", sol: "CHEOPE" },
    { def: "Si dice di un'occasione che capita nel momento giusto", sol: "PROPIZIA" },
    { def: "Il celebre esploratore veneziano autore de Il Milione", sol: "POLO" },
    { def: "Lo stato con la città santa della Mecca", sol: "ARABIA" },
    { def: "La membrana elastica che vibra nel fonografo", sol: "DIAFRAMMA" },
    { def: "Il pittore veneto autore della Venere di Urbino", sol: "TIZIANO" },
    { def: "La storica via di Roma che partiva da Piazza Venezia", sol: "FORIIMPERIALI" },
    { def: "L'eroe troiano figlio di Priamo ucciso da Achille", sol: "ETTORE" },
    { def: "Il verso emesso dal cane per minacciare", sol: "RINGHIO" },
    { def: "L'autore del romanzo Il fu Mattia Pascal", sol: "PIRANDELLO" },
    { def: "Lo strumento che serve per misurare la profondità marina", sol: "SCANDAGLIO" },
    { def: "La leggendaria regina di Palmira che sfidò Roma", sol: "ZENOBIA" },
    { def: "Il monte della Grecia dove risiedevano gli Dei", sol: "OLIMPO" },
    { def: "Lo scrittore che inventò il commissario Maigret", sol: "SIMENON" },
    { def: "Il nome della celebre spia che operò durante la Grande Guerra", sol: "MATAHARI" },
    { def: "La parte bianca dell'occhio", sol: "SCLERA" },
    { def: "Il metallo usato per galvanizzare il ferro e proteggerlo", sol: "ZINCO" },
    { def: "Il cavaliere della Tavola Rotonda figlio di Lancillotto", sol: "GALAHAD" },
    { def: "Lo stato che ha come simbolo il fiore di loto", sol: "INDIA" },
    { def: "Il navigatore genovese che scoprì il Canada per l'Inghilterra", sol: "CABOTO" },
    { def: "Il dolce di Siena con canditi, mandorle e spezie", sol: "PANFORTE" },
    { def: "Lo strumento per visualizzare l'attività del cuore", sol: "ELETTROCARDIOGRAFO" },
    { def: "La città con la grotta dove apparve la Madonna nel 1858", sol: "LOURDES" },
    { def: "Il nome del padre di Ismaele nella Bibbia", sol: "ABRAMO" },
    { def: "Il minerale che si trova sotto forma di cristallo di rocca", sol: "QUARZO" },
    { def: "La capitale della Polonia", sol: "VARSAVIA" },
    { def: "Il gioco in cui si devono indovinare i nomi delle persone", sol: "NOMICECO" },
    { def: "Il compositore della musica del Guglielmo Tell", sol: "ROSSINI" },
    { def: "La regione con la città di Trieste", sol: "FRIULI" },
    { def: "Il termine che indica una vincita totale alle corse", sol: "SBANCATA" },
    { def: "La sostanza usata per produrre la dinamite", sol: "NITROGLICERINA" },
    { def: "Il profeta che fu inghiottito da una balena", sol: "GIONA" },
    { def: "La parte anteriore della nave", sol: "PRUA" },
    { def: "Lo scienziato che scoprì i raggi X", sol: "RONTGEN" },
    { def: "Il leggendario arciere svizzero che colpì la mela", sol: "GUGLIELMOTELL" },
    { def: "La capitale dell'Irlanda", sol: "DUBLINO" },
    { def: "Si dice di un'opera che è stata fatta a regola d'arte", sol: "MAGISTRALE" },
    { def: "La storica annunciatrice televisiva definita 'Signorina Buonasera'", sol: "ANNUNCIATRICE" },
    { def: "Il nome del primo cane inviato nello spazio dai russi", sol: "LAIKA" },
    { def: "Il minerale che compone le stalattiti e le stalagmiti", sol: "CALCITE" },
    { def: "Si dice di un'azione compiuta con estrema rapidità", sol: "FULMINEA" },
    { def: "Il celebre esploratore che raggiunse il Polo Sud per primo", sol: "AMUNDSEN" },
    { def: "Il pittore spagnolo autore del quadro Guernica", sol: "PICASSO" },
    { def: "La famosa piazza di Roma con la Fontana dei Quattro Fiumi", sol: "NAVONA" },
    { def: "Il gas contenuto nelle bollicine dello spumante", sol: "ANIDRIDE" },
    { def: "L'eroe mitologico che portava il mondo sulle spalle", sol: "ATLANTE" },
    { def: "La capitale della Romania", sol: "BUCAREST" },
    { def: "Il termine che indica il verso del cavallo", sol: "NITIRO" },
    { def: "Lo strumento per misurare l'intensità del terremoto", sol: "SISMOGRAFO" },
    { def: "La leggendaria sposa di Ulisse che tesseva la tela", sol: "PENELOPE" },
    { def: "Il nome della famosa reggia costruita da Luigi XIV", sol: "VERSAILLES" },
    { def: "La parte trasparente anteriore dell'occhio", sol: "CORNEA" },
    { def: "Lo scienziato polacco che formulò la teoria eliocentrica", sol: "COPERNICO" },
    { def: "La capitale dell'Ungheria", sol: "BUDAPEST" },
    { def: "Il cavaliere della Tavola Rotonda che amò la regina Ginevra", sol: "LANCILLOTTO" },
    { def: "Il navigatore che scoprì la Florida cercando la fonte della giovinezza", sol: "PONCE" },
    { def: "Il dolce tipico siciliano a base di ricotta e canditi", sol: "CASSATA" },
    { def: "Il pittore francese autore delle Ninfee", sol: "MONET" },
    { def: "La città francese famosa per il Palazzo dei Papi", sol: "AVIGNONE" },
    { def: "Il nome del primo uomo creato secondo la Genesi", sol: "ADAMO" },
    { def: "Il minerale che costituisce la sabbia più comune", sol: "SILICE" },
    { def: "La capitale della Croazia", sol: "ZAGABRIA" },
    { def: "Il gioco in cui si devono colpire dei birilli con una palla", sol: "BOWLING" },
    { def: "Il compositore d'opera autore della Norma", sol: "BELLINI" },
    { def: "La regione con la città di Aosta", sol: "VALLEDAOSTA" },
    { def: "Il termine che indica il punteggio zero nel tennis", sol: "LOVE" },
    { def: "La sostanza dolce prodotta dalle api", sol: "MIELE" },
    { def: "Il profeta biblico che divise le acque del Mar Rosso", sol: "MOSE" },
    { def: "La parte posteriore della nave", sol: "POPA" },
    { def: "Il deserto che occupa gran parte dell'Africa australe", sol: "KALAHARI" },
    { def: "Il film con il giovane orfano cresciuto dai lupi Mowgli", sol: "LIBRODELLAGIUNGLA" },
    { def: "Il leggendario re spartano che morì alle Termopili", sol: "LEONIDA" },
    { def: "Il colore che rappresenta la speranza", sol: "VERDE" },
    { def: "Si dice di un'opera scritta con grande maestria", sol: "ECCELSA" },
    { def: "Lo è Alessandro quando deve andare al negozio di animali", sol: "IMBARAZZATO" },
    { def: "Il gruppo di amici che non si ferma mai", sol: "VAISEMPRE" },
    { def: "Se Vincenzo è Junior, chi sarà il Senior?", sol: "VINO" },
    { def: "Vincenzo Pio Guido...", sol: "FUOCO" },
    { def: "L'ironico titolo nobiliare dato ad Alessandro", sol: "REDEGLISCEMI" },
    { def: "Il secondo nome di Simone coniato dal padre di Fabio", sol: "GAETANO" },
    { def: "Il soprannome di Francesco con il finale numerico", sol: "CICCIO33" },
    { def: "L'insetto a cui è associato Antonio, padre di Francesco", sol: "ZANZARA" },
    { def: "Il trivellone è la dote goliardica attribuita a lui", sol: "FABIO" },
    { def: "Il nome del padre di Fabio, autore di molti meme", sol: "GIORGIO" },
    { def: "Vincenzo lo è di nome e... di 'Vino'", sol: "JUNIOR" },
    { def: "Il secondo nome di battesimo di Vincenzo", sol: "PIO" },
    { def: "Il colore del pesce che mise in crisi Alessandro", sol: "ROSSO" },
    { def: "L'attrezzo meccanico associato a Fabio", sol: "TRIVELLA" },
    { def: "L'amico che condivide il nome con Gaetano", sol: "SIMONE" },
    { def: "La storica rassegna canora nata nel 1951", sol: "SANREMO" },
    { def: "Il metallo che compone le monete da un euro", sol: "NICHEL" },
    { def: "Lo stretto che separa l'Europa dall'Africa", sol: "GIBILTERRA" },
    { def: "La stella che indica la direzione del Nord", sol: "POLARE" },
    { def: "Il ponte che unisce Venezia alla terraferma", sol: "LIBERTA" },
    { def: "Lo sport di Roger Federer", sol: "TENNIS" },
    { def: "Il processo di trasformazione del bruco", sol: "METAMORFOSI" },
    { def: "La ghiandola che produce l'adrenalina", sol: "SURRENE" },
    { def: "Il materiale di cui sono fatte le candele", sol: "CERA" },
    { def: "Sinonimo ricercato di 'abbigliamento'", sol: "ABBIGLIAMENTO" },
    { def: "Il contrario di 'effimero'", sol: "ETERNO" },
    { def: "Verbo che indica l'azione di togliere le rughe", sol: "LEVIGARE" },
    { def: "Sostantivo che indica una lode eccessiva e servile", sol: "ADULAZIONE" },
    { def: "Aggettivo per chi dimostra grande audacia", sol: "TEMERARIO" },
    { def: "Sinonimo di 'indispensabile' o 'essenziale'", sol: "IMPRESCINDIBILE" },
    { def: "Il modo verbale che esprime incertezza o desiderio", sol: "CONGIUNTIVO" },
    { def: "Un errore grammaticale o di sintassi", sol: "SOLECISMO" },
    { def: "Sinonimo di 'inizio' o 'esordio'", sol: "ALBORI" },
    { def: "Aggettivo per un discorso chiaro e scorrevole", sol: "FLUIDO" },
    { def: "Sostantivo che indica la mancanza di ordine", sol: "ANARCHIA" },
    { def: "Sinonimo di 'profumo' intenso e gradevole", sol: "FRAGRANZA" },
    { def: "L'opposto di 'conciso' o 'breve'", sol: "PROLISSO" },
    { def: "Il prefisso che indica 'al di sopra'", sol: "IPER" },
    { def: "Aggettivo per un suono che reca fastidio", sol: "STRIDENTE" },
    { def: "Sinonimo di 'ostacolo' o 'impedimento'", sol: "INTOPPO" },
    { def: "Verbo che significa 'mettere in ordine' i documenti", sol: "ARCHIVIARE" },
    { def: "Sostantivo per un'improvvisa ispirazione", sol: "ESTRO" },
    { def: "L'aggettivo per chi non sa né leggere né scrivere", sol: "ANALFABETA" },
    { def: "Sinonimo di 'povertà' estrema", sol: "INDIGENZA" },
    { def: "Il sostantivo che indica la tipica parlata regionale", sol: "DIALETTO" },
    { def: "Aggettivo per un'azione compiuta di nascosto", sol: "FURTIVA" },
    { def: "Sinonimo di 'stancante' o 'faticoso'", sol: "ESTENUANTE" },
    { def: "Verbo che indica il riflettere profondamente", sol: "MEDITARE" },
    { def: "Sostantivo per un falso ragionamento", sol: "FALLACIA" },
    { def: "Aggettivo per un metallo che si può ridurre in fili", sol: "DUTTILE" },
    { def: "Il contrario di 'altruista'", sol: "EGOISTA" },
    { def: "Sinonimo di 'chiasso' o 'confusione'", sol: "BACCANO" },
    { def: "Aggettivo per un terreno che non produce nulla", sol: "ARIDO" },
    { def: "Il verbo che indica il crollo di un edificio", sol: "ROVINARE" },
    { def: "Sinonimo di 'astio' o 'risentimento'", sol: "RANCORE" },
    { def: "L'aggettivo per una persona che parla molto", sol: "LOGORROICA" },
    { def: "Il sostantivo per la dignità professionale", sol: "DEONTOLOGIA" },
    { def: "Sinonimo di 'misterioso' o 'oscuro'", sol: "ENIGMATICO" },
    { def: "Verbo che significa 'rendere nullo'", sol: "INVALIDARE" },
    { def: "Aggettivo per una luce molto intensa", sol: "ABBAGLIANTE" },
    { def: "Sostantivo per una piccola lite tra amici", sol: "DIBATTITO" },
    { def: "Il contrario di 'precedente'", sol: "SUCCESSIVO" },
    { def: "Sinonimo di 'vile' o 'codardo'", sol: "PUSILLANIME" },
    { def: "Aggettivo per un cibo che stuzzica l'appetito", sol: "SUCCULENTO" },
    { def: "Sostantivo per la parte finale di un libro", sol: "EPILOGO" },
    { def: "Il verbo che indica il far uscire fumo", sol: "ESALARE" },
    { def: "Sinonimo di 'felicità' immensa", sol: "EUFORIA" },
    { def: "Aggettivo per chi non cambia mai idea", sol: "OSTINATO" },
    { def: "Sostantivo per il desiderio di vendetta", sol: "RIVALSA" },
    { def: "Il contrario di 'monotono'", sol: "VARIO" },
    { def: "Sinonimo di 'astuzia' sottile", sol: "SAGACIA" },
    { def: "Aggettivo per un corpo che si spezza facilmente", sol: "FRAGILE" },
    { def: "Sostantivo per l'introduzione di un'opera", sol: "PROLOGO" },
    { def: "Sinonimo di 'innato' o 'naturale'", sol: "CONGENITO" },
    { def: "Aggettivo per un'azione che non ha scopo", sol: "VANA" },
    { def: "Sostantivo che indica il timore del futuro", sol: "APPRENSIONE" },
    { def: "Verbo che significa 'togliere il disturbo'", sol: "CONGEDARSI" },
    { def: "Sinonimo di 'misterioso' o 'segreto'", sol: "ARCANO" },
    { def: "Aggettivo per chi mangia con eccessiva voracità", sol: "INGORDO" },
    { def: "Sostantivo per un'offesa alla dignità", sol: "OLTRAGGIO" },
    { def: "Il contrario di 'superfluo'", sol: "ESSENZIALE" },
    { def: "Verbo che indica il parlare sottovoce", sol: "SUSSURRARE" },
    { def: "Sinonimo di 'follia' o 'pazzia'", sol: "DEMENZA" },
    { def: "Aggettivo per chi non mostra alcuna paura", sol: "IMPARDITO" },
    { def: "Sostantivo che indica la ripetizione di una vocale", sol: "ASSONANZA" },
    { def: "L'opposto di 'stabile' o 'fermo'", sol: "PRECARIO" },
    { def: "Verbo che significa 'dare inizio' a una cerimonia", sol: "INAUGURARE" },
    { def: "Sinonimo di 'fastidio' o 'seccatura'", sol: "TEDIO" },
    { def: "Aggettivo per un terreno che non può essere coltivato", sol: "IMPRODUTTIVO" },
    { def: "Sostantivo per una lode spassionata", sol: "ENCOMIO" },
    { def: "Il contrario di 'moderno'", sol: "VETUSTO" },
    { def: "Verbo che indica l'azione di rendere più bello", sol: "ABBELLIRE" },
    { def: "Sinonimo di 'ricchezza' o 'abbondanza'", sol: "OPULENZA" },
    { def: "Aggettivo per chi si adira facilmente", sol: "IRASCIBILE" },
    { def: "L'opposto di 'umile'", sol: "SUPERBO" },
    { def: "Verbo che significa 'prendere il posto di qualcuno'", sol: "SOSTITUIRE" },
    { def: "Sinonimo di 'errore' commesso per sbadataggine", sol: "SVISTA" },
    { def: "Aggettivo per un suono acuto e penetrante", sol: "LACERANTE" },
    { def: "Sostantivo per una profonda tristezza", sol: "MALINCONIA" },
    { def: "Il contrario di 'concreto'", sol: "ASTRATTO" },
    { def: "Verbo che indica il camminare senza meta", sol: "VAGARE" },
    { def: "Sinonimo di 'astuzia' maligna", sol: "PERFIDIA" },
    { def: "Aggettivo per chi parla in modo molto forbito", sol: "ELOQUENTE" },
    { def: "Sostantivo per un improvviso desiderio", sol: "GIRIBIZZO" },
    { def: "L'opposto di 'severo'", sol: "INDULGENTE" },
    { def: "Verbo che significa 'mettere paura'", sol: "INTIMIDIRE" },
    { def: "Sinonimo di 'pace' o 'quiete'", sol: "SERENITA" },
    { def: "Aggettivo per un oggetto che si può trasportare", sol: "MOBILE" },
    { def: "Sostantivo per un'attesa vana e prolungata", sol: "PASTOIE" },
    { def: "Il contrario di 'spontaneo'", sol: "FORZATO" },
    { def: "Verbo che indica il riflettere sul passato", sol: "RIMEMBRARE" },
    { def: "Sinonimo di 'coraggio' eroico", sol: "VALORE" },
    { def: "Aggettivo per un clima molto caldo e umido", sol: "AFA" },
    { def: "Sostantivo per una persona che guida gli altri", sol: "MENTORE" },
    { def: "L'opposto di 'chiaro' o 'limpido'", sol: "TORBIDO" },
    { def: "Verbo che significa 'rendere più forte'", sol: "CORROBORARE" },
    { def: "Sinonimo di 'destino' ineluttabile", sol: "FATO" },
    { def: "Aggettivo per chi non ha mai abbastanza", sol: "INSATIABILE" },
    { def: "Sostantivo per la fine di un'epoca", sol: "TRAMONTO" },
    { def: "Il contrario di 'raro'", sol: "COMUNE" },
    { def: "Verbo che indica il salire su una nave", sol: "IMBARCARSI" },
];