const croceDomande = [
    { def: "Capoluogo della Liguria, porto importante", sol: "GENOVA" },
    { def: "La città dei canali e delle gondole", sol: "VENEZIA" },
    { def: "Fiume che attraversa Roma", sol: "TEVERE" },
    { def: "Il satellite naturale della Terra", sol: "LUNA" },
    { def: "Il pianeta più grande del sistema solare", sol: "GIOVE" },
    { def: "Capitale della Francia", sol: "PARIGI" },
    { def: "Il metallo prezioso giallo per eccellenza", sol: "ORO" },
    { def: "Strumento a corde pizzicate di forma triangolare", sol: "ARPA" },
    { def: "Regione italiana con capoluogo Palermo", sol: "SICILIA" },
    { def: "Uccello simbolo della pace", sol: "COLOMBA" },
    { def: "Lago più grande d'Italia", sol: "GARDA" },
    { def: "Il pianeta rosso", sol: "MARTE" },
    { def: "La montagna più alta del mondo", sol: "EVEREST" },
    { def: "Lo scrittore della Divina Commedia", sol: "DANTE" },
    { def: "Il compositore della Quinta Sinfonia", sol: "BEETHOVEN" },
    { def: "Grande isola con capoluogo Cagliari", sol: "SARDEGNA" },
    { def: "Il frutto della vite", sol: "UVA" },
    { def: "Strumento a fiato dai suoni squillanti", sol: "TROMBA" },
    { def: "La capitale della Spagna", sol: "MADRID" },
    { def: "Il re dei felini", sol: "LEONE" },
    { def: "Antico anfiteatro di Roma", sol: "COLOSSEO" },
    { def: "La moneta unica europea", sol: "EURO" },
    { def: "Leggendario cavallo alato della mitologia greca", sol: "PEGASO" },
    { def: "Pittore della Gioconda", sol: "LEONARDO" },
    { def: "Scienziato della teoria della relatività", sol: "EINSTEIN" },
    { def: "Il numero che viene dopo il nove", sol: "DIECI" },
    { def: "Animale con la proboscide", sol: "ELEFANTE" },
    { def: "Lo sport nazionale degli americani con la mazza", sol: "BASEBALL" },
    { def: "Rettile lento dal guscio duro", sol: "TARTARUGA" },
    { def: "La capitale del Giappone", sol: "TOKYO" },
    { def: "Strumento a tastiera di Chopin", sol: "PIANOFORTE" },
    { def: "Il colore del cielo sereno", sol: "AZZURRO" },
    { def: "Fiume più lungo d'Italia", sol: "PO" },
    { def: "Il vulcano attivo della Sicilia", sol: "ETNA" },
    { def: "Cetaceo più grande del mondo", sol: "BALENA" },
    { def: "La capitale della Germania", sol: "BERLINO" },
    { def: "Personaggio di Shakespeare, principe di Danimarca", sol: "AMLETO" },
    { def: "Il pianeta con gli anelli", sol: "SATURNO" },
    { def: "Felino delle nevi con il manto maculato", sol: "LEOPARDO" },
    { def: "Il metallo conduttore dei fili elettrici", sol: "RAME" },
    { def: "Inventore del telefono", sol: "BELL" },
    { def: "La regione italiana con la gondola nel simbolo", sol: "VENETO" },
    { def: "La stagione dei fiori", sol: "PRIMAVERA" },
    { def: "Il più famoso quadro di Van Gogh con stelle", sol: "NOTTE" },
    { def: "Gioco di carte italiano con le briscole", sol: "BRISCOLA" },
    { def: "Il continente più grande del mondo", sol: "ASIA" },
    { def: "Il pianeta più vicino al Sole", sol: "MERCURIO" },
    { def: "La capitale d'Australia", sol: "CANBERRA" },
    { def: "Scrittore di Don Chisciotte", sol: "CERVANTES" },
    { def: "Animale che cambia colore per mimetizzarsi", sol: "CAMALEONTE" },
    { def: "La montagna sacra del Giappone", sol: "FUJI" },
    { def: "Strumento di navigazione che indica il nord", sol: "BUSSOLA" },
    { def: "Il matematico della mela che cadde", sol: "NEWTON" },
    { def: "Il deserto più grande del mondo", sol: "SAHARA" },
    { def: "La capitale del Brasile", sol: "BRASILIA" },
    { def: "Personaggio Disney figlio di Mufasa", sol: "SIMBA" },
    { def: "Lo sport invernale con le racchette", sol: "SCI" },
    { def: "Pittore olandese delle Girasoli", sol: "VANGOGH" },
    { def: "Il gas che respiriamo per vivere", sol: "OSSIGENO" },
    { def: "Il gioco degli scacchi ha questa figura con la corona", sol: "REGINA" },
    { def: "Scrittore di Pinocchio", sol: "COLLODI" },
    { def: "La più piccola pianeta del sistema solare", sol: "MERCURIO" },
    { def: "Il colore ottenuto mescolando rosso e blu", sol: "VIOLA" },
    { def: "L'isola di Robinson Crusoe nell'immaginario", sol: "ISOLA" },
    { def: "La regione con il capoluogo Firenze", sol: "TOSCANA" },
    { def: "Il mare a est dell'Italia", sol: "ADRIATICO" },
    { def: "Animale che dorme tutto l'inverno", sol: "ORSO" },
    { def: "Il simbolo chimico dell'acqua ha due di questo gas", sol: "IDROGENO" },
    { def: "La capitale dell'Argentina", sol: "BUENOSAIRES" },
    { def: "Il navigatore che scoprì l'America nel 1492", sol: "COLOMBO" },
    { def: "Sport olimpico praticato in piscina", sol: "NUOTO" },
    { def: "La montagna che divide Italia e Francia nelle Alpi", sol: "BIANCO" },
    { def: "Il colore della bandiera italiana al centro", sol: "BIANCO" },
    { def: "L'inventore della stampa a caratteri mobili", sol: "GUTENBERG" },
    { def: "Il palazzo del governo italiano a Roma", sol: "QUIRINALE" },
    { def: "Lo strumento usato dall'astronomo per osservare le stelle", sol: "TELESCOPIO" },
    { def: "Rettile senza zampe", sol: "SERPENTE" },
    { def: "La capitale della Russia", sol: "MOSCA" },
    { def: "Il termine musicale per suono più acuto", sol: "SOPRANO" },
    { def: "Antico guerriero romano", sol: "GLADIATORE" },
    { def: "Il continente al Polo Sud", sol: "ANTARTIDE" },
    { def: "Lo sport con il pallone ovale", sol: "RUGBY" },
    { def: "Il re degli scacchi è sotto attacco: situazione di", sol: "SCACCO" },
    { def: "Lo scrittore de I Promessi Sposi", sol: "MANZONI" },
    { def: "Frutto tropicale giallo a forma di mezzaluna", sol: "BANANA" },
    { def: "Il pianeta con la grande macchia rossa", sol: "GIOVE" },
    { def: "La capitale del Portogallo", sol: "LISBONA" },
    { def: "Il componente principale della fotosintesi clorofilliana", sol: "CLOROFILLA" },
    { def: "Il matematico di Siracusa famoso per il principio", sol: "ARCHIMEDE" },
    { def: "La regione italiana del Vesuvio", sol: "CAMPANIA" },
    { def: "Il colore della foglia in autunno avanzato", sol: "GIALLO" },
    { def: "Sport con racchette e volano", sol: "BADMINTON" },
    { def: "Lo strumento del chirurgo per tagliare", sol: "BISTURI" },
    { def: "Il paese asiatico della Grande Muraglia", sol: "CINA" },
    { def: "La figura geometrica a tre lati", sol: "TRIANGOLO" },
    { def: "Il re degli scacchi: il pezzo più importante", sol: "RE" },
    { def: "L'artista fiorentino che scolpì il David", sol: "MICHELANGELO" },
    { def: "Il mare che bagna Napoli", sol: "TIRRENO" },
    { def: "La regione del Piemonte con il capoluogo", sol: "TORINO" },
    { def: "Strumento di misura della temperatura", sol: "TERMOMETRO" },
    { def: "Il navigatore italiano che diede il nome all'America", sol: "VESPUCCI" },
];
