const FRASI_RUOTA = [
    { frase: "LA DOLCE VITA", categoria: "Cinema Italiano" },
    { frase: "COLAZIONE DA TIFFANY", categoria: "Cinema" },
    { frase: "IL PADRINO", categoria: "Cinema" },
    { frase: "TITANIC", categoria: "Cinema" },
    { frase: "FORREST GUMP", categoria: "Cinema" },
    { frase: "PULP FICTION", categoria: "Cinema" },
    { frase: "SCHINDLER'S LIST", categoria: "Cinema" },
    { frase: "IL SIGNORE DEGLI ANELLI", categoria: "Cinema" },
    { frase: "HARRY POTTER", categoria: "Cinema" },
    { frase: "INDIANA JONES", categoria: "Cinema" },
    { frase: "STAR WARS", categoria: "Cinema" },
    { frase: "JURASSIC PARK", categoria: "Cinema" },
    { frase: "IL RE LEONE", categoria: "Animazione" },
    { frase: "ALLA RICERCA DI NEMO", categoria: "Animazione" },
    { frase: "SHREK", categoria: "Animazione" },
    { frase: "TOY STORY", categoria: "Animazione" },
    { frase: "CENERENTOLA", categoria: "Favola" },
    { frase: "BIANCANEVE", categoria: "Favola" },
    { frase: "LA BELLA E LA BESTIA", categoria: "Favola" },
    { frase: "CAPPUCCETTO ROSSO", categoria: "Favola" },
    { frase: "PIZZA MARGHERITA", categoria: "Cucina" },
    { frase: "PASTA AL POMODORO", categoria: "Cucina" },
    { frase: "TIRAMISÙ", categoria: "Cucina" },
    { frase: "CARBONARA", categoria: "Cucina" },
    { frase: "LASAGNE AL FORNO", categoria: "Cucina" },
    { frase: "RISOTTO ALLA MILANESE", categoria: "Cucina" },
    { frase: "GELATO AL CIOCCOLATO", categoria: "Cucina" },
    { frase: "PARMIGIANA DI MELANZANE", categoria: "Cucina" },
    { frase: "COLOSSEO", categoria: "Monumenti" },
    { frase: "TORRE DI PISA", categoria: "Monumenti" },
    { frase: "FONTANA DI TREVI", categoria: "Monumenti" },
    { frase: "PIAZZA SAN MARCO", categoria: "Monumenti" },
    { frase: "IL DAVID DI MICHELANGELO", categoria: "Arte" },
    { frase: "LA GIOCONDA", categoria: "Arte" },
    { frase: "LA NASCITA DI VENERE", categoria: "Arte" },
    { frase: "L'URLO DI MUNCH", categoria: "Arte" },
    { frase: "DOMENICA IN", categoria: "TV Italiana" },
    { frase: "GRANDE FRATELLO", categoria: "TV Italiana" },
    { frase: "CHI VUOL ESSERE MILIONARIO", categoria: "TV Italiana" },
    { frase: "STRISCIA LA NOTIZIA", categoria: "TV Italiana" },
    { frase: "PORTA A PORTA", categoria: "TV Italiana" },
    { frase: "AMICI DI MARIA", categoria: "TV Italiana" },
    { frase: "BALLANDO CON LE STELLE", categoria: "TV Italiana" },
    { frase: "L'ISOLA DEI FAMOSI", categoria: "TV Italiana" },
    { frase: "FORMULA UNO", categoria: "Sport" },
    { frase: "CAMPIONI DEL MONDO", categoria: "Sport" },
    { frase: "OLIMPIADI INVERNALI", categoria: "Sport" },
    { frase: "COPPA DEL MONDO", categoria: "Sport" },
    { frase: "TOUR DE FRANCE", categoria: "Sport" },
    { frase: "WIMBLEDON", categoria: "Sport" },
    { frase: "SUPER BOWL", categoria: "Sport" },
    { frase: "MARATONA DI NEW YORK", categoria: "Sport" },
    { frase: "SOTTO IL SOLE DI RICCIONE", categoria: "Musica" },
    { frase: "AZZURRO", categoria: "Musica" },
    { frase: "VOLARE NEL BLU DIPINTO DI BLU", categoria: "Musica" },
    { frase: "ROMAGNA MIA", categoria: "Musica" },
    { frase: "FELICITÀ", categoria: "Musica" },
    { frase: "GRANDE GRANDE GRANDE", categoria: "Musica" },
    { frase: "BOCCA DI ROSA", categoria: "Musica" },
    { frase: "LUCIO BATTISTI", categoria: "Cantanti" },
    { frase: "ANDREA BOCELLI", categoria: "Cantanti" },
    { frase: "EROS RAMAZZOTTI", categoria: "Cantanti" },
    { frase: "ZUCCHERO FORNACIARI", categoria: "Cantanti" },
    { frase: "VASCO ROSSI", categoria: "Cantanti" },
    { frase: "TIZIANO FERRO", categoria: "Cantanti" },
    { frase: "LAURA PAUSINI", categoria: "Cantanti" },
    { frase: "GIANNI MORANDI", categoria: "Cantanti" },
    { frase: "MAMMA MIA", categoria: "Espressioni" },
    { frase: "CHE BELLA GIORNATA", categoria: "Espressioni" },
    { frase: "PIANO PIANO", categoria: "Espressioni" },
    { frase: "TUTTO BENE", categoria: "Espressioni" },
    { frase: "IN BOCCA AL LUPO", categoria: "Espressioni" },
    { frase: "ACQUA IN BOCCA", categoria: "Espressioni" },
    { frase: "FARE IL FURBO", categoria: "Espressioni" },
    { frase: "PRENDERE DUE PICCIONI", categoria: "Espressioni" },
    { frase: "BUONA FORTUNA", categoria: "Espressioni" },
    { frase: "COLPO DI FULMINE", categoria: "Espressioni" },
    { frase: "ROMEO E GIULIETTA", categoria: "Letteratura" },
    { frase: "LA DIVINA COMMEDIA", categoria: "Letteratura" },
    { frase: "IL PICCOLO PRINCIPE", categoria: "Letteratura" },
    { frase: "DON CHISCIOTTE", categoria: "Letteratura" },
    { frase: "I PROMESSI SPOSI", categoria: "Letteratura" },
    { frase: "CIME TEMPESTOSE", categoria: "Letteratura" },
    { frase: "ORGOGLIO E PREGIUDIZIO", categoria: "Letteratura" },
    { frase: "GUERRE STELLARI", categoria: "Fantascienza" },
    { frase: "IL PIANETA DELLE SCIMMIE", categoria: "Fantascienza" },
    { frase: "RITORNO AL FUTURO", categoria: "Fantascienza" },
    { frase: "MATRIX", categoria: "Fantascienza" },
    { frase: "AVATAR", categoria: "Fantascienza" },
    { frase: "INTERSTELLAR", categoria: "Fantascienza" },
    { frase: "2001 ODISSEA NELLO SPAZIO", categoria: "Fantascienza" },
    { frase: "VENEZIA", categoria: "Città Italiane" },
    { frase: "FIRENZE", categoria: "Città Italiane" },
    { frase: "NAPOLI", categoria: "Città Italiane" },
    { frase: "PALERMO", categoria: "Città Italiane" },
    { frase: "TORINO", categoria: "Città Italiane" },
    { frase: "BOLOGNA", categoria: "Città Italiane" },
    { frase: "BARI", categoria: "Città Italiane" },
];
